### ISSUE TITLE
[Bug] d.mon: Rendering failed: Expecting 1235x201 image but got 474x571 image.

### ISSUE THREAD

**Issue by neteler** [OSGeo/grass#1062]
**Describe the bug**

When using `d.mon` over a non-local connection (e.g., using `ssh -Y server` and in this case the lightweight monitor is very useful) it tends to run into the following error (note: typos are possible, I had to use `tesseract` to OCR the error message) from the wx error window:

```
Rendering failed: Expecting 1235x201 image but got 474x571 image.

Reason:

Traceback (most recent call last):
File "/home/mneteler/software/grass_master/dist.x86_64-pc-linux-gnu/gui/wxpython/mapwin/buffered.py", line 921, in_updateM
self. Map.Render(force=render,
File "/home/mneteler/software/grass_master/dist.x86_64-pc-linux-gnu/gui/wxpython/mapdisp/main.py", line 296, in Render
return Map.Render(self, *args, **kwargs)
File "/home/mneteler/software/grass_master/dist.x86_64-pe-linux-gnu/gui/wxpython/core/render. py", line 1277, in Render
self.renderMgr.Render(force, windres)
File "/home/mneteler/software/grass_master/dist.x86_64-pc-linux-gnu/gui/wxpython/core/render. py", line 627, in Render
if self,_renderLayers(eny, force) == 0:
File "/home/mneteler/software/grass_master/dist.x86_64-pc-linux-gnu/gui/wxpython/core/render. py", line 566, in_renderLayers
layer. GetRenderMgr().updateProgress.emit(env=env, layer=layer)
File "/home/mneteler/software/grass_master/dist.x86_64-pc-linux-gnu/etc/python/grass/pydispatch/signal.py*, line 230, in emit
dispatcher. send(signal=self, *args, **kwargs)
File "/home/mneteler/software/grass_master/dist.x86_64-pc-linux-gnu/etc/python/grass/pydispatch/dispatcher. py", line 345, in send
response = robustapply.robustapply(
File "/home/mneteler/software/grass_master/dist.x86_64-pc-linux-gnu/etc/python/grass/pydispatch/robustapply.py", line 60, in robustApply
return receiver(*arguments, **named)
File "/home/mneteler/software/grass_master/dist.x86_64-pc-linux-gnu/gui/wxpython/core/render.py", line 770, in ReportProgress
self.renderDone.emit(env=env)
File "/home/mneteler/software/grass_master/dist.x86_64-pc-linux-gnu/etc/python/grass/pydispatch/signal.py*, line 230, in emit
dispatcher. send(signal=self, *args, **kwargs)
File "/home/mneteler/software/grass_master/dist.x86_64-pc-linux-gnu/etc/python/grass/pydispatch/dispatcher. py", line 345, in send
response = robustapply.robustapply(
File "/home/mneteler/software/grass_master/dist.x86_64-pc-linux-gnu/etc/python/grass/pydispatch/robustapply.py", line 60, in robustApply
return receiver(*arguments, **named)
File "/home/mneteler/software/grass_master/dist.x86_64-pc-linux-gnu/gui/wxpython/core/render. py", line 673, in OnRenderDone
raise GException(_("Rendering failed: %s" % msg))
core.gcmd.GException: Rendering failed: Expecting 1235x201 image
but got 474x571 image.
```

I suspect that a kind of race condition occurs.

**To Reproduce**

1. connect to a remote GRASS GIS instance (e.g. `ssh`)
2. open a GRASS GIS session and run `d.mon wx0`
3. Wait till it comes up and resize the monitor
4. Run `d.rast elevation` (NC dataset) and the error may occur

**Expected behavior**

The very useful standalone monitor `d.mon` should not run into troubles.

**Screenshots**

**System description (please complete the following information):**

- Operating System: Fedora 32
- GRASS GIS version: master (the problem exists for years, though)

**Comment by pmozbert** [comment]
I noticed this behavior with d.mon when I ran d.vect immediatly after calling d.mon start.  I found that if I put a sleep of several seconds after calling d.mon, then the errors were avoided.   The sleep gave the display time to fully render.

**Comment by tmszi** [comment]
> I noticed this behavior with d.mon when I ran d.vect immediatly after calling d.mon start. I found that if I put a sleep of several seconds after calling d.mon, then the errors were avoided. The sleep gave the display time to fully render.

Yes I can confirm this bug.

Steps to reproduce the behavior:

1. `d.mon start=wx0 && d.rast elevation`
2.  `d.redraw`

**Error message:**

![d_mon_error_message](https://user-images.githubusercontent.com/50632337/97952924-36b88500-1d9f-11eb-936b-82608896862e.png)

**Comment by tmszi** [comment]
I got a similar error (post above) as you. Could @neteler try test this [PR](https://github.com/OSGeo/grass/pull/1064)?

**Comment by neteler** [comment]
Your PR #1064 works nicely! I tested both a ssh connection as well as your local use case.
