### ISSUE TITLE
[Feat] GUI: catch at startup if PERMANENT mapset is missing

### ISSUE THREAD

**Issue by neteler** [OSGeo/grass#1084]
**Is your feature request related to a problem? Please describe.**

Maybe a rare issue but probably easy to catch:

If the `PERMANENT` mapset is absent, then the GUI crashes with obscure message(s):

`ERROR: Unable to open element file <> for <DEFAULT_WIND@PERMANENT>`

If possible, please catch this situation.

**To reproduce**

I downloaded an extra NC sample mapset ([MODIS LST](https://grass.osgeo.org/sampledata/north_carolina/nc_spm_mapset_modis2015_2016_lst.zip)) from the GRASS site and forgot to extract it in the proper location.

**Comment by wenzeslaus** [comment]
I'm not able to reproduce the exactly same behavior, but I think the errors I get in GUI are result of the above. I don't get a GUI crash (but the GUI _is_ unusable). What I get is things like this:

```
  File "".../dist.x86_64-pc-linux-gnu/gui/wxpython/core/gthread.py", line 141, in OnDone
    event.ondone(event)
  File "".../dist.x86_64-pc-linux-gnu/gui/wxpython/mapwin/buffered.py", line 931, in _onUpdateMap
    self._runUpdateMap()
  File "".../dist.x86_64-pc-linux-gnu/gui/wxpython/mapwin/buffered.py", line 936, in _runUpdateMap
    self._updateM(self.render, self.renderVector)
  File "".../dist.x86_64-pc-linux-gnu/gui/wxpython/mapwin/buffered.py", line 958, in _updateM
    self.Map.Render(force=render, windres=self._properties.resolution)
  File "".../dist.x86_64-pc-linux-gnu/gui/wxpython/core/render.py", line 1339, in Render
    self.renderMgr.Render(force, windres)
  File "".../dist.x86_64-pc-linux-gnu/gui/wxpython/core/render.py", line 661, in Render
    env = self.GetRenderEnv(windres)
  File "".../dist.x86_64-pc-linux-gnu/gui/wxpython/core/render.py", line 617, in GetRenderEnv
    env["GRASS_REGION"] = self.Map.SetRegion(windres)
  File "".../dist.x86_64-pc-linux-gnu/gui/wxpython/core/render.py", line 1192, in SetRegion
    region = self.AdjustRegion()
  File ".../dist.x86_64-pc-linux-gnu/gui/wxpython/core/render.py", line 932, in AdjustRegion
    mapwidth = abs(self.region["e"] - self.region["w"])
KeyError: 'e'
```

I get this both with main and with 7.8, so unrelated to any of the recent changes.

The `DEFAULT_WIND@PERMANENT` is not related to GUI, I get the same with `grass ... --exec` and `g.region -p`:

```
grass ~/Downloads/nc_spm_mapset_modis2015_2016_lst/modis_lst --exec g.region -p
```

```
Starting GRASS GIS...
Cleaning up temporary files...
Executing <g.region -p> ...
ERROR: Unable to open element file <> for <DEFAULT_WIND@PERMANENT>
Execution of <g.region -p> finished.
Cleaning up default sqlite database ...
Cleaning up temporary files...
```

The issue is with the general startup code. It checks that the mapset is valid, but it does not check the location.

Related to this are two other issues. First, `g.region -p` checks for `DEFAULT_WIND` (in PERMANENT). I'm not sure why. It seems unnecessary.

Second, the error message seems to think it knows about the structure: "element file x for y" but clearly it does not know anything. In other words, a more specialized message is needed for this type of mapset element/object.

**Comment by wenzeslaus** [comment]
I actually don't know how to reproduce the originally reported issue just using GUI. However, starting in a mapset, closing the GUI, deleting the PERMANENT mapset of that location, and then starting the GUI again results in an error:

![Screenshot from 2023-05-17 09-06-09](https://github.com/OSGeo/grass/assets/5449060/762cf433-0503-4b30-9458-00121cb63b9e)

And two tracebacks in the terminal (similar to the one above):

```
(wxgui.py:1359120): Gtk-WARNING **: 09:05:54.137: Negative content height -9 (allocation 1, extents 5x5) while allocating gadget (node button, owner GtkToggleButton)
Traceback (most recent call last):
  File "/home/vpetras/.local/lib/python3.8/site-packages/wx/core.py", line 3407, in <lambda>
    lambda event: event.callable(*event.args, **event.kw) )
  File ".../dist.x86_64-pc-linux-gnu/gui/wxpython/wxgui.py", line 95, in show_main_gui
    mainframe = GMFrame(parent=None, id=wx.ID_ANY, workspace=self.workspaceFile)
  File ".../dist.x86_64-pc-linux-gnu/gui/wxpython/main_window/frame.py", line 209, in __init__
    self.NewDisplay(show=False)
  File ".../dist.x86_64-pc-linux-gnu/gui/wxpython/main_window/frame.py", line 451, in NewDisplay
    self.currentPage.maptree = LayerTree(
  File ".../dist.x86_64-pc-linux-gnu/gui/wxpython/lmgr/layertree.py", line 155, in __init__
    self.mapdisplay = createNewMapDisplay(layertree=self)
  File ".../dist.x86_64-pc-linux-gnu/gui/wxpython/main_window/frame.py", line 430, in CreateNewMapDisplay
    mapdisplay = MapPanel(
  File ".../dist.x86_64-pc-linux-gnu/gui/wxpython/mapdisp/frame.py", line 195, in __init__
    self.MapWindow2D.InitZoomHistory()
  File ".../dist.x86_64-pc-linux-gnu/gui/wxpython/mapwin/buffered.py", line 1955, in InitZoomHistory
    self.Map.region["n"],
KeyError: 'n'

(wxgui.py:1359120): Gtk-WARNING **: 09:06:23.217: Negative content height -9 (allocation 1, extents 5x5) while allocating gadget (node button, owner GtkToggleButton)
Traceback (most recent call last):
  File ".../dist.x86_64-pc-linux-gnu/gui/wxpython/core/gthread.py", line 141, in OnDone
    event.ondone(event)
  File ".../dist.x86_64-pc-linux-gnu/gui/wxpython/mapwin/buffered.py", line 931, in _onUpdateMap
    self._runUpdateMap()
  File ".../dist.x86_64-pc-linux-gnu/gui/wxpython/mapwin/buffered.py", line 936, in _runUpdateMap
    self._updateM(self.render, self.renderVector)
  File ".../dist.x86_64-pc-linux-gnu/gui/wxpython/mapwin/buffered.py", line 958, in _updateM
    self.Map.Render(force=render, windres=self._properties.resolution)
  File ".../dist.x86_64-pc-linux-gnu/gui/wxpython/core/render.py", line 1338, in Render
    self.renderMgr.Render(force, windres)
  File ".../dist.x86_64-pc-linux-gnu/gui/wxpython/core/render.py", line 661, in Render
    env = self.GetRenderEnv(windres)
  File ".../dist.x86_64-pc-linux-gnu/gui/wxpython/core/render.py", line 617, in GetRenderEnv
    env["GRASS_REGION"] = self.Map.SetRegion(windres)
  File ".../dist.x86_64-pc-linux-gnu/gui/wxpython/core/render.py", line 1192, in SetRegion
    region = self.AdjustRegion()
  File ".../dist.x86_64-pc-linux-gnu/gui/wxpython/core/render.py", line 932, in AdjustRegion
    mapwidth = abs(self.region["e"] - self.region["w"])
KeyError: 'e'
```

Just to emphasize that this is not related to GUI itself, starting in text mode in the same situation happily proceeds:

$ grass8 --text
Starting GRASS GIS...

          __________  ___   __________    _______________
         / ____/ __ \/   | / ___/ ___/   / ____/  _/ ___/
        / / __/ /_/ / /| | \__ \\_  \   / / __ / / \__ \
       / /_/ / _, _/ ___ |___/ /__/ /  / /_/ // / ___/ /
       \____/_/ |_/_/  |_/____/____/   \____/___//____/

Welcome to GRASS GIS 8.3.dev (2edf3899e1)
...
```

But than it fails with `g.region -p`:

```
GRASS XY2/test:~ > g.region -p
ERROR: Unable to open element file <> for <DEFAULT_WIND@PERMANENT>
```

This test was done using an XY location.

**Comment by wenzeslaus** [comment]
Given there is no direct connection to the recent changes and the conditions which trigger it are little obscure, I'm moving this to the next milestone.
