### ISSUE TITLE
[Bug] GUI fails to start since commit 5fd8c29

### ISSUE THREAD

**Issue by infrastation** [OSGeo/grass#1156]
**Describe the bug**
On the current master branch since commit 5fd8c29 the GUI fails to start with the following output:
```text
$ grass79 --gui
Starting GRASS GIS...
Cleaning up temporary files...

          __________  ___   __________    _______________
         / ____/ __ \/   | / ___/ ___/   / ____/  _/ ___/
        / / __/ /_/ / /| | \__ \\_  \   / / __ / / \__ \
       / /_/ / _, _/ ___ |___/ /__/ /  / /_/ // / ___/ /
       \____/_/ |_/_/  |_/____/____/   \____/___//____/

Welcome to GRASS GIS 7.9.dev (547ded6c0)
GRASS GIS homepage:                      https://grass.osgeo.org
This version running through:            Bash Shell (/bin/bash)
Help is available with the command:      g.manual -i
See the licence terms with:              g.version -c
See citation options with:               g.version -x
If required, restart the GUI with:       g.gui wxpython
When ready to quit enter:                exit

Launching <wxpython> GUI in the background, please wait...
To run a command as administrator (user "root"), use "sudo <command>".
See "man sudo_root" for details.

GRASS UK_ALOS_reprojected/PERMANENT:~ > Traceback (most recent call last):
  File "/home/denis/grass_exec/grass79/gui/wxpython/wxgui.py", line 106, in OnInit
    workspace=self.workspaceFile)
  File "/home/denis/grass_exec/grass79/gui/wxpython/lmgr/frame.py", line 151, in __init__
    self.notebook = self._createNoteBook()
  File "/home/denis/grass_exec/grass79/gui/wxpython/lmgr/frame.py", line 389, in _createNoteBook
    parent=self.notebook, giface=self._giface, simpleEditorHandler=self.OnSimpleEditor)
  File "/home/denis/grass_exec/grass79/gui/wxpython/lmgr/pyshell.py", line 52, in __init__
    useStockId=(sys.platform != "darwin"))
  File "/usr/lib/python3/dist-packages/wx/py/shell.py", line 268, in __init__
    *args, **kwds)
TypeError: __init__() got an unexpected keyword argument 'useStockId'
OnInit returned false, exiting...
Error in atexit._run_exitfuncs:
wx._core.wxAssertionError: C++ assertion "GetEventHandler() == this" failed at ../src/common/wincmn.cpp(478) in ~wxWindowBase(): any pushed event handlers must have been removed

GRASS UK_ALOS_reprojected/PERMANENT:~ > exit
Cleaning up default sqlite database ...
Cleaning up temporary files...
Done.

Goodbye from GRASS GIS
```

**System description (please complete the following information):**
- Operating System: GNU/Linux Ubuntu 18.04 64-bit
- GRASS GIS version: master branch (currently at commit 31113f1)

**Comment by nilason** [comment]
What version of python and wxpython do you use?

**Comment by infrastation** [comment]
Here is what I can gather from dpkg:
```text
ii  python3.5                              3.5.2-2ubuntu0~16.04.4
ii  python3.6                              3.6.9-1~18.04ubuntu1.3
ii  python-wxgtk3.0                        3.0.2.0+dfsg-7
ii  python-wxversion                       3.0.2.0+dfsg-7
ii  python3-wxgtk4.0                       4.0.1+dfsg-2
```
The default Python version seems to be 3.6:
```text
$ python3 --version
Python 3.6.9
```
I do not know how to tell which wxpython belongs to the problem space. You are welcome to give specific commands to run or patches to test.

**Comment by neteler** [comment]
To print the Python and wxPython version numbers, run

```
python3 -c "import sys, wx; print(sys.version); print(wx.version())"
```

**Comment by nilason** [comment]
This is probably due to unsupported method call, will look into this tomorrow (if someone doesn't beat me to it).

For a temporary fix locally, try change the `/home/denis/grass_exec/grass79/gui/wxpython/lmgr/pyshell.py`:L
48-52:

from:
```
        self.shell = PyShell(parent=self, id=wx.ID_ANY,
                             introText=self.intro,
                             locals={'gs': grass,
                                     'AddLayer': self.AddLayer},
                             useStockId=(sys.platform != "darwin"))
```

to:
```
        self.shell = PyShell(parent=self, id=wx.ID_ANY,
                             introText=self.intro,
                             locals={'gs': grass,
                                     'AddLayer': self.AddLayer})
```

**Comment by infrastation** [comment]
Thank you. With the suggested change the GUI is able to start again..

```text
$ python3 -c "import sys, wx; print(sys.version); print(wx.version())"
3.6.9 (default, Oct  8 2020, 12:12:24) 
[GCC 8.4.0]
4.0.1 gtk3 (phoenix)
```

Let me know if you need any other information.

**Comment by petrasovaa** [comment]
> This is probably due to unsupported method call, will look into this tomorrow (if someone doesn't beat me to it).
> 

I will leave the PR for you, but I looked at the problem, the parameter was added in wxPython 4.0.2:
https://github.com/wxWidgets/Phoenix/pull/834

Good we haven't backported it yet.

**Comment by nilason** [comment]
> I will leave the PR for you, but I looked at the problem, the parameter was added in wxPython 4.0.2:
> [wxWidgets/Phoenix#834](https://github.com/wxWidgets/Phoenix/pull/834)

Thanks for looking this up. Very unfortunate API changes to wxPython are not tracked in its documentation.

> Good we haven't backported it yet.

Indeed.

I added a PR #1160, which addresses this issue.
