### ISSUE TITLE
[Bug] winGRASS 7.9dev: wx._core.wxAssertionError: C++ assertion "GetEventHandler() == this" failed

### ISSUE THREAD

**Issue by hellik** [OSGeo/grass#1213]
**Describe the bug**

starting winGRASS 7.9dev results in:

```
Cleaning up temporary files...

          __________  ___   __________    _______________
         / ____/ __ \/   | / ___/ ___/   / ____/  _/ ___/
        / / __/ /_/ / /| | \__ \\_  \   / / __ / / \__ \
       / /_/ / _, _/ ___ |___/ /__/ /  / /_/ // / ___/ /
       \____/_/ |_/_/  |_/____/____/   \____/___//____/

Welcome to GRASS GIS 7.9.dev (373033590)
GRASS GIS homepage:                      https://grass.osgeo.org
This version running through:            Command Prompt (C:\WINDOWS\system32\cmd.exe)
Help is available with the command:      g.manual -i
See the licence terms with:              g.version -c
See citation options with:               g.version -x
If required, restart the GUI with:       g.gui wxpython
When ready to quit enter:                exit

Launching <wxpython> GUI in the background, please wait...
Microsoft Windows [Version 10.0.19042.685]
(c) 2020 Microsoft Corporation. Alle Rechte vorbehalten.

C:\>Traceback (most recent call last):
  File "C:\OSGEO4~1\apps\grass\grass79\gui\wxpython\wxgui.py", line 106, in OnInit
    workspace=self.workspaceFile)
  File "C:\OSGEO4~1\apps\grass\grass79\gui\wxpython\lmgr\frame.py", line 152, in __init__
    self.notebook = self._createNoteBook()
  File "C:\OSGEO4~1\apps\grass\grass79\gui\wxpython\lmgr\frame.py", line 322, in _createNoteBook
    parent=self.notebook, giface=self._giface)
  File "C:\OSGEO4~1\apps\grass\grass79\gui\wxpython\datacatalog\catalog.py", line 55, in __init__
    self.infoBar = InfoBar(self)
  File "C:\OSGEO4~1\apps\grass\grass79\gui\wxpython\gui_core\infobar.py", line 30, in __init__
    IB.InfoBar.__init__(self, parent)
  File "C:\OSGEO4~1\apps\Python37\lib\site-packages\wx\lib\agw\infobar.py", line 379, in __init__
    bmp = GetCloseButtonBitmap(self, sizeBmp, colBg)
  File "C:\OSGEO4~1\apps\Python37\lib\site-packages\wx\lib\agw\infobar.py", line 226, in GetCloseButtonBitmap
    wx.RendererNative.Get().DrawTitleBarBitmap(win, dc, wx.Rect(size), wx.TITLEBAR_BUTTON_CLOSE, flags)
AttributeError: 'RendererNative' object has no attribute 'DrawTitleBarBitmap'
OnInit returned false, exiting...
Error in atexit._run_exitfuncs:
wx._core.wxAssertionError: C++ assertion "GetEventHandler() == this" failed at ..\..\src\common\wincmn.cpp(478) in wxWindowBase::~wxWindowBase(): any pushed event handlers must have been removed
```

**To Reproduce**

1. download latest daily winGRASS 7.9dev in OSGeo4W
2. start winGRASS 7.9dev with wxGUI
3. See error

**Expected behavior**

wxGUI starts normally

**System description (please complete the following information):**

```
C:\>g.version -g
version=7.9.dev
date=2020
revision=373033590
build_date=2020-12-24
build_platform=x86_64-w64-mingw32
build_off_t_size=8
```

**Comment by petrasovaa** [comment]
This is bug in wxPython:
https://github.com/wxWidgets/Phoenix/issues/1425
It is already solved but I couldn't find in which version. I suggest to workaround it in #1214 but I couldn't test it on Windows.

**Comment by hellik** [comment]
fix locally applied, GUI starts again. PR approved.
