### ISSUE TITLE
[Bug] Fail gracefully when there are no tests

### ISSUE THREAD

**Issue by wenzeslaus** [OSGeo/grass#1445]
**Describe the bug**

When there are no tests in the current directory or any of its subdirectories, the tests fails with traceback and error:

```
TypeError: '>=' not supported between instances of 'NoneType' and 'int'
```

This is because there is 0 files and the file_pass_per (percentage of files passing tests) is None which is a case which needs special handling, although it is still an failure.

**To Reproduce**

Compile latest GRASS GIS (or use 7.8) and:

```
grass --tmp-location XY --exec g.extension g.download.location
mkdir /tmp/grassdata
grass --tmp-location XY --exec g.download.location dbase=/tmp/grassdata url=https://grass.osgeo.org/sampledata/north_carolina/nc_spm_08_grass7.zip
cd grass/gis/source/code
mkdir /tmp/empty_dir
cd /tmp/empty_dir
grass --tmp-location XY --exec python3 -m grass.gunittest.main --grassdata /tmp/grassdata/ --location nc_spm_08_grass7 --location-type nc --min-success 80
```

where `grass` is your installed/compiled GRASS GIS executable or a path to it and `/tmp/` is where you want to work.

**Expected behavior**

Fail with non-zero return code like when the min success rate is not achieved, but without a traceback. Not finding any tests should be considered a failure. Optionally, there could be a new command line flag to consider that okay.

**Screenshots**

From (unrelated) https://github.com/OSGeo/grass/issues/1342#issuecomment-796053039:

```
grass79 --tmp-location XY --exec python3 -m grass.gunittest.main --grassdata /tmp/grassdata/ --location nc_spm_08_grass7 --location-type nc --min-success 80
Starting GRASS GIS...
Creating new GRASS GIS location <tmploc>...
Cleaning up temporary files...
Executing <python3 -m grass.gunittest.main --grassdata /tmp/grassdata/ --location nc_spm_08_grass7 --location-type nc --min-success 80> ...

Executed 0 test files in 0:00:00.009054.
From them 0 files (unknown percentage) were successful and 0 files (unknown percentage) failed.
Traceback (most recent call last):
  File "/usr/lib64/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/mneteler/software/grass_master/dist.x86_64-pc-linux-gnu/etc/python/grass/gunittest/main.py", line 227, in <module>
    sys.exit(main())
  File "/home/mneteler/software/grass_master/dist.x86_64-pc-linux-gnu/etc/python/grass/gunittest/main.py", line 221, in main
    if reporter.file_pass_per >= args.min_success:
TypeError: '>=' not supported between instances of 'NoneType' and 'int'
```

**System description (please complete the following information):**

- GRASS GIS version 7.8 and development version

**Additional context**

Introduced with `--min-success` (6962e31db16991f4bf6eb85b5853ec9c34c22405).

**Comment by leopoldch** [comment]
Hi, is this already solved ? 
This is what I get after reproducing :

```
Executed 0 test files in 0:00:00.000422.
From them 0 files (unknown percentage) were successful and 0 files (unknown percentage) failed.
No tests found or executed
```

**Comment by wenzeslaus** [comment]
Looks correct to me. You can look at the source code in python/grass/gunittest to confirm. Search for a couple of words from the sentence.

**Comment by Agrim863** [comment]
“Hi! I noticed that the current output now correctly reports ‘No tests found or executed’ without a traceback. Could you please confirm if this issue is considered resolved, or if any further refinement is needed?”
Regards
Agrim

**Comment by gkneighb** [comment]
This is no longer reproducible on current `main`. `python/grass/gunittest/main.py` now has an early-return guard before the `file_pass_per` comparison:

```python
# python/grass/gunittest/main.py:269-271
if not reporter.test_files:
    return "No tests found or executed"
if reporter.file_pass_per >= args.min_success:
    return 0
```

So when there are zero test files the function returns the friendly message before ever comparing `None >= int`. Safe to close.

**Comment by echoix** [comment]
Thanks for checking again!
