### ISSUE TITLE
[Bug] t.rast.algebra does not check if output exists before executing the requested expression

### ISSUE THREAD

**Issue by NikosAlexandris** [OSGeo/grass#1472]
**Observed behavior**

In the following example, `t.rast.algebra` used in a `for` loop, does not check if the output space-time raaster dataset already exists.  Hence, it first executes the requested expression and afterwards checks and notifies

```
 100%
ERROR: Space time raster dataset <output_space_time_raster_dataset_4> is already
in the database. Use the overwrite flag.
Traceback (most recent call last):
  File "/osgeo/grass/dist.x86_64-pc-linux-gnu/scripts/t.rast.algebra", line 132, in <module>
    sys.exit(main())
  File "/osgeo/grass/dist.x86_64-pc-linux-gnu/scripts/t.rast.algebra", line 124, in main
    pc = p.parse(expression, basename, grass.script.overwrite())
  File "/osgeo/grass/dist.x86_64-pc-linux-gnu/etc/python/grass/temporal/temporal_raster_algebra.py", line 110, in parse
    self.parser.parse(expression)
  File "/home/nik/code/miniconda3/envs/py385/lib/python3.8/site-packages/ply/yacc.py", line 333, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/home/nik/code/miniconda3/envs/py385/lib/python3.8/site-packages/ply/yacc.py", line 1120, in parseopt_notrack
    p.callable(pslice)
  File "/osgeo/grass/dist.x86_64-pc-linux-gnu/etc/python/grass/temporal/temporal_raster_algebra.py", line 121, in p_statement_assign
    TemporalRasterBaseAlgebraParser.p_statement_assign(self, t)
  File "/osgeo/grass/dist.x86_64-pc-linux-gnu/etc/python/grass/temporal/temporal_raster_base_algebra.py", line 755, in p_statement_assign
    resultstds = open_new_stds(t[1], self.stdstype,
  File "/osgeo/grass/dist.x86_64-pc-linux-gnu/etc/python/grass/temporal/open_stds.py", line 155, in open_new_stds
    sp = check_new_stds(name, type, dbif, overwrite)
  File "/osgeo/grass/dist.x86_64-pc-linux-gnu/etc/python/grass/temporal/open_stds.py", line 123, in check_new_stds
    msgr.fatal(_("Space time %(sp)s dataset <%(name)s> is already in the"
  File "/osgeo/grass/dist.x86_64-pc-linux-gnu/etc/python/grass/pygrass/messages/__init__.py", line 269, in fatal
    raise FatalError(message)
grass.exceptions.FatalError: Space time raster dataset <output_space_time_raster_dataset_4> is already in the database. Use the overwrite flag.
```

**To Reproduce**

Using existing space time raster datasets, such as `input_space_time_raster_dataset_4_unscaled` and `input_space_time_raster_dataset_5_unscaled`, run:

```
for BAND in 4 5 ;do
    t.rast.algebra \
    expression="output_space_time_raster_dataset_${BAND} = input_space_time_raster_dataset_${BAND}_unscaled * 0.001 + 0.5" \
    basename=output_space_time_raster_dataset_${BAND} \
    suffix=time \
    nprocs=40
done
```

**Expected behavior**

`t.rast.algebra` should warn for an existing output space time dataset before even trying to execute the requested expression.

**System description (please complete the following information):**

- Operating System: Linux
- GRASS GIS version 7.8.5dev (2020)

**Comment by veroandreo** [comment]
I confirm this happens in grass-dev too. 
The thing is it first checks if basenames exist, if they do, it fails immediately. Otherwise it runs the requested operation. 
Indeed, it should also check if the output STRDS exists before executing the expression.
