### ISSUE TITLE
[Bug] v.patch segmentation fault when DB table absent in one input map

### ISSUE THREAD

**Issue by dmci99** [OSGeo/grass#1488]
**Describe the bug**
A segmentation fault is returned when two vector layers are patched and one does not have an attribute table attached. 

**To Reproduce**
Using the Spearfish dataset:

`v.extract input=roads output=roads_interstate where="label='interstate'"`
`v.extract input=roads output=roads_primary where="label LIKE 'primary%'"`
`v.extract input=roads output=roads_secondary where="label LIKE 'secondary%'"`

`##here I patch one set of vectors without -e`
`v.patch input=roads_primary,roads_secondary out=roads_12`

`v.patch -e input=roads_12,roads_interstate output=roads_patch`
`Segmentation fault`

**Expected behavior**
Print an  error message stating that one attribute table is missing (similar to the column check that `v.patch` does)

**System description (please complete the following information):**

- Operating System: GNU/Linux Debian 10 4.19.0-13-amd64 
- GRASS GIS version GRASS GIS 7.9.dev

**Additional context**
[Related thread on the grass-user mailing list](https://lists.osgeo.org/pipermail/grass-user/2021-March/082279.html)

**Comment by neteler** [comment]
I can confirm the bug. Here `gdb` output, using [spearfish60_grass7](https://grass.osgeo.org/sampledata/spearfish_grass70data-0.3.tar.gz):

```
grass79 ~/grassdata/spearfish60_grass7/user1/

v.extract input=roads output=roads_interstate where="label='interstate'"
v.extract input=roads output=roads_primary where="label LIKE 'primary%'"
v.extract input=roads output=roads_secondary where="label LIKE 'secondary%'"

##here I patch one set of vectors without -e
v.patch input=roads_primary,roads_secondary out=roads_12

## subsequently DB connection is missing:
v.db.connect -p roads_12
Map <roads_12> is not connected to a database

gdb v.patch
GNU gdb (GDB) Fedora 10.1-4.fc33
Copyright (C) 2020 Free Software Foundation, Inc.
...

r -e input=roads_12,roads_interstate output=roads_patch
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7f18442 in db_get_table_number_of_columns (table=0x0) at table.c:140
140	    return table->numColumns;

(gdb) bt full
#0  0x00007ffff7f18442 in db_get_table_number_of_columns (table=0x0) at table.c:140
No locals.
#1  0x0000000000404009 in main (argc=4, argv=0x7fffffffd5d8) at main.c:225
        ncols = 0
        col = 0
        i = 0
        ret = 0
        in_name = 0x47e570 "roads_12"
        out_name = 0x47e4f0 "roads_patch"
        meta_name = 0x47e570 "roads_12"
        bbox_name = 0x0
        module = 0x7ffff7f0af08 <state+40>
        old = 0x7ffff7f0af68 <state+136>
        new = 0x47e180
        bbox = 0x47e240
        append = 0x47e3c0
        table_flag = 0x47e370
        no_topo = 0x47e410
        no_input_topo_flag = 0x7ffff7f0af38 <state+88>
        force_z_flag = 0x47e320
        InMap = {format = 0, temporary = 0, dblnk = 0x84e6d0, plus = {version = {topo = {major = 0, minor = 0, back_major = 0, back_minor = 0}, spidx = {
                major = 0, minor = 0, back_major = 0, back_minor = 0}, cidx = {major = 0, minor = 0, back_major = 0, back_minor = 0}}, with_z = 0, 
            spidx_with_z = 0, off_t_size = 0, head_size = 0, spidx_head_size = 0, cidx_head_size = 0, release_support = 0, port = {byte_order = 0, 
              off_t_size = 0, dbl_cnvrt = "\000\000\000\000\000\000\000", flt_cnvrt = "\000\000\000", lng_cnvrt = "\000\000\000", 
              int_cnvrt = "\000\000\000", shrt_cnvrt = "\000", off_t_cnvrt = "\000\000\000\000\000\000\000", dbl_quick = 0, flt_quick = 0, lng_quick = 0, 
              int_quick = 0, shrt_quick = 0, off_t_quick = 0}, spidx_port = {byte_order = 0, off_t_size = 0, dbl_cnvrt = "\000\000\000\000\000\000\000", 
              flt_cnvrt = "\000\000\000", lng_cnvrt = "\000\000\000", int_cnvrt = "\000\000\000", shrt_cnvrt = "\000", 
              off_t_cnvrt = "\000\000\000\000\000\000\000", dbl_quick = 0, flt_quick = 0, lng_quick = 0, int_quick = 0, shrt_quick = 0, off_t_quick = 0}, 
            cidx_port = {byte_order = 0, off_t_size = 0, dbl_cnvrt = "\000\000\000\000\000\000\000", flt_cnvrt = "\000\000\000", lng_cnvrt = "\000\000\000", 
              int_cnvrt = "\000\000\000", shrt_cnvrt = "\000", off_t_cnvrt = "\000\000\000\000\000\000\000", dbl_quick = 0, flt_quick = 0, lng_quick = 0, 
              int_quick = 0, shrt_quick = 0, off_t_quick = 0}, mode = 0, built = 0, box = {N = 0, S = 0, E = 0, W = 0, T = 0, B = 0}, Node = 0x0, 
            Line = 0x0, Area = 0x0, Isle = 0x0, n_plines = 0, n_llines = 0, n_blines = 0, n_clines = 0, n_flines = 0, n_klines = 0, n_vfaces = 0, 
            n_hfaces = 0, n_nodes = 0, n_edges = 0, n_lines = 0, n_areas = 0, n_isles = 0, n_faces = 0, n_volumes = 0, n_holes = 0, alloc_nodes = 0, 
            alloc_edges = 0, alloc_lines = 0, alloc_areas = 0, alloc_isles = 0, alloc_faces = 0, alloc_volumes = 0, alloc_holes = 0, Node_offset = 0, 
            Edge_offset = 0, Line_offset = 0, Area_offset = 0, Isle_offset = 0, Volume_offset = 0, Hole_offset = 0, Spidx_built = 0, Spidx_new = 0, 
            Spidx_file = 0, spidx_fp = {file = 0x0, start = 0x0, current = 0x0, end = 0x0, size = 0, alloc = 0, loaded = 0}, Node_spidx_offset = 0, 
            Line_spidx_offset = 0, Area_spidx_offset = 0, Isle_spidx_offset = 0, Face_spidx_offset = 0, Volume_spidx_offset = 0, Hole_spidx_offset = 0, 
            Node_spidx = 0x84c170, Line_spidx = 0x84cc60, Area_spidx = 0x84b840, Isle_spidx = 0x84d730, Face_spidx = 0x0, Volume_spidx = 0x0, 
            Hole_spidx = 0x0, update_cidx = 0, n_cidx = 0, a_cidx = 5, cidx = 0x84e320, cidx_up_to_date = 0, coor_size = 0, coor_mtime = 0, uplist = {
              do_uplist = 0, uplines = 0x0, uplines_offset = 0x0, alloc_uplines = 0, n_uplines = 0, upnodes = 0x0, alloc_upnodes = 0, n_upnodes = 0}}, 
          open = 1428335138, mode = 0, level = 1, head_only = 1, support_updated = 0, name = 0x84e510 "roads_12", mapset = 0x84e5b0 "user1", 
          location = 0x84e5d0 "spearfish60_grass7", gisdbase = 0x84e5f0 "/home/mneteler/grassdata", next_line = 0, constraint = {region_flag = 0, box = {
              N = 0, S = 0, E = 0, W = 0, T = 0, B = 0}, type_flag = 0, type = 0, field_flag = 0, field = 0}, proj = 0, hist_fp = 0x41ffb0, dgraph = {
            line_type = 0, graph_s = {iErrno = 0, Version = 0 '\000', Endian = 0 '\000', NodeAttrSize = 0, EdgeAttrSize = 0, aOpaqueSet = {
                0 <repeats 16 times>}, cNode = 0, cHead = 0, cTail = 0, cAlone = 0, cEdge = 0, nnCost = 0, Flags = 0, nFamily = 0, nOptions = 0, 
              pNodeTree = 0x0, pEdgeTree = 0x0, pNodeBuffer = 0x0, iNodeBuffer = 0, pEdgeBuffer = 0x0, iEdgeBuffer = 0, edgePrioritizer = {cEdge = 0, 
                iEdge = 0, pEdgePri32Item = 0x0, pvAVL = 0x0}, nodePrioritizer = {pvAVL = 0x0}}, spCache = {nStartNode = 0, NodeHeap = {index = 0, count = 0, block = 0, pnode = 0x0}, pvVisited = 0x0, pvPredist = 0x0}, edge_fcosts = 0x0, edge_bcosts = 0x0, node_costs = 0x0, cost_multip = 0}, head = {organization = 0x84f720 "US Army Const. Eng. Rsch. Lab", date = 0x84e640 "5/26/90", user_name = 0x84e660 "mneteler", map_name = 0x84e680 "Output from v.patch", source_date = 0x84e620 "1961", orig_scale = 24000, comment = 0x84e550 "new roads at 1:24000 for Spearfish database", proj = 1, plani_zone = 13, digit_thresh = 18.288, coor_version = {major = 0, minor = 0, back_major = 0, back_minor = 0}, with_z = 0, size = 0, head_size = 0, port = {byte_order = 0, off_t_size = 0, dbl_cnvrt = "\000\000\000\000\000\000\000", flt_cnvrt = "\000\000\000", lng_cnvrt = "\000\000\000", int_cnvrt = "\000\000\000", shrt_cnvrt = "\000", off_t_cnvrt = "\000\000\000\000\000\000\000", dbl_quick = 0, flt_quick = 0, lng_quick = 0, int_quick = 0, shrt_quick = 0, off_t_quick = 0}, last_offset = 0, recycle = 0x0}, dig_fp = {file = 0x0, start = 0x0, current = 0x0, end = 0x0, size = 0, alloc = 0, loaded = 0}, fInfo = {i = 0, ogr = {driver_name = 0x0, dsn = 0x0, layer_name = 0x0, where = 0x0, driver = 0x0, ds = 0x0, layer = 0x0, dbdriver = 0x0, dsn_options = 0x0, layer_options = 0x0, cache = {lines = 0x0, lines_types = 0x0, lines_cats = 0x0, lines_alloc = 0, lines_num = 0, lines_next = 0, fid = 0, sf_type = SF_GEOMETRY, ctype = 0}, feature_cache = 0x0, offset = {array = 0x0, array_num = 0, array_alloc = 0}, next_line = 0}, pg = {conninfo = 0x0, db_name = 0x0, schema_name = 0x0, table_name = 0x0, where = 0x0, fid_column = 0x0, geom_column = 0x0, feature_type = SF_GEOMETRY, coor_dim = 0, srid = 0, dbdriver = 0x0, fi = 0x0, inTransaction = 0, conn = 0x0, res = 0x0, cursor_name = 0x0, cursor_fid = 0, next_line = 0, cache = {lines = 0x0, lines_types = 0x0, lines_cats = 0x0, lines_alloc = 0, lines_num = 0, lines_next = 0, fid = 0, sf_type = SF_GEOMETRY, ctype = 0}, offset = {array = 0x0, array_num = 0, array_alloc = 0}, topogeom_column = 0x0, toposchema_name = 0x0, toposchema_id = 0, topo_geo_only = 0}}, site_att = 0x0, n_site_att = 0, n_site_dbl = 0, n_site_str = 0}
        OutMap = {format = 0, temporary = 0, dblnk = 0x0, plus = {version = {topo = {major = 0, minor = 0, back_major = 0, back_minor = 0}, spidx = {major = 0, minor = 0, back_major = 0, back_minor = 0}, cidx = {major = 0, minor = 0, back_major = 0, back_minor = 0}}, with_z = 0, spidx_with_z = 0, off_t_size = 0, head_size = 0, spidx_head_size = 0, cidx_head_size = 0, release_support = 0, port = {byte_order = 0, off_t_size = 0, dbl_cnvrt = "\000\000\000\000\000\000\000", flt_cnvrt = "\000\000\000", lng_cnvrt = "\000\000\000", int_cnvrt = "\000\000\000", shrt_cnvrt = "\000", off_t_cnvrt = "\000\000\000\000\000\000\000", dbl_quick = 0, flt_quick = 0, lng_quick = 0, int_quick = 0, shrt_quick = 0, off_t_quick = 0}, spidx_port = {byte_order = 0, off_t_size = 0, dbl_cnvrt = "\000\000\000\000\000\000\000", flt_cnvrt = "\000\000\000", lng_cnvrt = "\000\000\000", int_cnvrt = "\000\000\000", shrt_cnvrt = "\000", off_t_cnvrt = "\000\000\000\000\000\000\000", dbl_quick = 0, flt_quick = 0, lng_quick = 0, int_quick = 0, shrt_quick = 0, off_t_quick = 0}, cidx_port = {byte_order = 0, off_t_size = 0, dbl_cnvrt = "\000\000\000\000\000\000\000", flt_cnvrt = "\000\000\000", lng_cnvrt = "\000\000\000", int_cnvrt = "\000\000\000", shrt_cnvrt = "\000", off_t_cnvrt = "\000\000\000\000\000\000\000", dbl_quick = 0, flt_quick = 0, lng_quick = 0, int_quick = 0, shrt_quick = 0, off_t_quick = 0}, mode = 0, built = 0, box = {N = 0, S = 0, E = 0, W = 0, T = 0, B = 0}, Node = 0x0, Line = 0x0, Area = 0x0, Isle = 0x0, n_plines = 0, n_llines = 0, n_blines = 0, n_clines = 0, n_flines = 0, n_klines = 0, n_vfaces = 0, n_hfaces = 0, n_nodes = 0, n_edges = 0, n_lines = 0, n_areas = 0, n_isles = 0, n_faces = 0, n_volumes = 0, n_holes = 0, alloc_nodes = 0, alloc_edges = 0, alloc_lines = 0, alloc_areas = 0, alloc_isles = 0, alloc_faces = 0, alloc_volumes = 0, alloc_holes = 0, Node_offset = 0, Edge_offset = 0, Line_offset = 0, Area_offset = 0, Isle_offset = 0, Volume_offset = 0, Hole_offset = 0, Spidx_built = 0, Spidx_new = 0, Spidx_file = 0, spidx_fp = {file = 0x0, start = 0x0, current = 0x0, end = 0x0, size = 0, alloc = 0, loaded = 0}, Node_spidx_offset = 0, Line_spidx_offset = 0, Area_spidx_offset = 0, Isle_spidx_offset = 0, Face_spidx_offset = 0, Volume_spidx_offset = 0, Hole_spidx_offset = 0, Node_spidx = 0x0, Line_spidx = 0x0, Area_spidx = 0x0, Isle_spidx = 0x0, Face_spidx = 0x0, Volume_spidx = 0x0, Hole_spidx = 0x0, update_cidx = 0, n_cidx = 0, a_cidx = 0, cidx = 0x0, cidx_up_to_date = 0, coor_size = 0, coor_mtime = 0, uplist = {do_uplist = 0, uplines = 0x0, uplines_offset = 0x0, alloc_uplines = 0, n_uplines = 0, upnodes = 0x0, alloc_upnodes = 0, n_upnodes = 0}}, open = 0, mode = 0, level = 0, head_only = 0, support_updated = 0, name = 0x0, mapset = 0x0, location = 0x0, gisdbase = 0x0, next_line = 0, constraint = {region_flag = 0, box = {N = 0, S = 0, E = 0, W = 0, T = 0, B = 0}, type_flag = 0, type = 0, field_flag = 0, field = 0}, proj = 0, hist_fp = 0x0, dgraph = {line_type = 0, graph_s = {iErrno = 0, Version = 0 '\000', Endian = 0 '\000', NodeAttrSize = 0, EdgeAttrSize = 0, aOpaqueSet = {0 <repeats 16 times>}, cNode = 0, cHead = 0, cTail = 0, cAlone = 0, cEdge = 0, nnCost = 0, Flags = 0, nFamily = 0, nOptions = 0, pNodeTree = 0x0, pEdgeTree = 0x0, pNodeBuffer = 0x0, iNodeBuffer = 0, pEdgeBuffer = 0x0, iEdgeBuffer = 0, edgePrioritizer = {cEdge = 0, iEdge = 0, pEdgePri32Item = 0x0, pvAVL = 0x0}, nodePrioritizer = {pvAVL = 0x0}}, spCache = {nStartNode = 0, NodeHeap = {index = 0, count = 0, block = 0, pnode = 0x0}, pvVisited = 0x0, pvPredist = 0x0}, edge_fcosts = 0x0, edge_bcosts = 0x0, node_costs = 0x0, cost_multip = 0}, head = {organization = 0x0, date = 0x0, user_name = 0x0, map_name = 0x0, source_date = 0x0, orig_scale = 0, comment = 0x0, proj = 0, plani_zone = 0, digit_thresh = 0, coor_version = {major = 0, minor = 0, back_major = 0, back_minor = 0}, with_z = 0, size = 0, head_size = 0, port = {byte_order = 0, off_t_size = 0, dbl_cnvrt = "\000\000\000\000\000\000\000", flt_cnvrt = "\000\000\000", lng_cnvrt = "\000\000\000", int_cnvrt = "\000\000\000", shrt_cnvrt = "\000", off_t_cnvrt = "\000\000\000\000\000\000\000", dbl_quick = 0, flt_quick = 0, lng_quick = 0, int_quick = 0, shrt_quick = 0, off_t_quick = 0}, last_offset = 0, recycle = 0x0}, dig_fp = {file = 0x0, start = 0x0, current = 0x0, end = 0x0, size = 0, alloc = 0, loaded = 0}, fInfo = {i = 0, ogr = {driver_name = 0x0, dsn = 0x0, layer_name = 0x0, where = 0x0, driver = 0x0, ds = 0x0, layer = 0x0, dbdriver = 0x0, dsn_options = 0x0, layer_options = 0x0, cache = {lines = 0x0, lines_types = 0x0, lines_cats = 0x0, lines_alloc = 0, lines_num = 0, lines_next = 0, fid = 0, sf_type = SF_GEOMETRY, ctype = 0}, feature_cache = 0x0, offset = {array = 0x0, array_num = 0, array_alloc = 0}, next_line = 0}, pg = {conninfo = 0x0, db_name = 0x0, schema_name = 0x0, table_name = 0x0, where = 0x0, fid_column = 0x0, geom_column = 0x0, feature_type = SF_GEOMETRY, coor_dim = 0, srid = 0, dbdriver = 0x0, fi = 0x0, inTransaction = 0, conn = 0x0, res = 0x0, cursor_name = 0x0, cursor_fid = 0, next_line = 0, cache = {lines = 0x0, lines_types = 0x0, lines_cats = 0x0, lines_alloc = 0, lines_num = 0, lines_next = 0, fid = 0, sf_type = SF_GEOMETRY, ctype = 0}, offset = {array = 0x0, array_num = 0, array_alloc = 0}, topogeom_column = 0x0, toposchema_name = 0x0, toposchema_id = 0, topo_geo_only = 0}}, site_att = 0x0, n_site_att = 0, n_site_dbl = 0, n_site_str = 0}
        BBoxMap = {format = 115, temporary = 0, dblnk = 0x20, plus = {version = {topo = {major = -185567141, minor = 32767, back_major = -185567141, back_minor = 32767}, spidx = {major = -1, minor = -1, back_major = 3, back_minor = 3}, cidx = {major = 1, minor = 0, back_major = -1, back_minor = 0}}, with_z = 0, spidx_with_z = 0, off_t_size = 0, head_size = 0, spidx_head_size = 0, cidx_head_size = 0, release_support = 0, port = {byte_order = 0, off_t_size = 0, dbl_cnvrt = "\000\000\000\000\000\000\000", flt_cnvrt = "\000\000\000", lng_cnvrt = "\000\000\000", int_cnvrt = "\000\000\000", shrt_cnvrt = "\000", off_t_cnvrt = "\000\000\000\000\000\000\000", dbl_quick = 0, flt_quick = 0, lng_quick = 0, int_quick = 0, shrt_quick = 0, off_t_quick = 0}, spidx_port = {byte_order = 0, off_t_size = 0, dbl_cnvrt = "\000\000\000\000\000\000\000", flt_cnvrt = "\000\000\000", lng_cnvrt = "\000\000\000", int_cnvrt = "\000\000\000", shrt_cnvrt = "\000", off_t_cnvrt = "\000\000\000\000\000\000\000", dbl_quick = 0, flt_quick = 0, lng_quick = 0, int_quick = 0, shrt_quick = 0, off_t_quick = 0}, cidx_port = {byte_order = 0, off_t_size = 0, dbl_cnvrt = "\000\000\000\000\000\000\000", flt_cnvrt = "\000\000\000", lng_cnvrt = "\000\000\000", int_cnvrt = "\000\000\000", shrt_cnvrt = "\000", off_t_cnvrt = "\000\000\000\000\000\000\000", dbl_quick = 0, flt_quick = 0, lng_quick = 0, int_quick = 0, shrt_quick = 0, off_t_quick = 0}, mode = 0, built = 0, box = {N = 0, S = 0, E = 0, W = 0, T = 0, B = 0}, Node = 0x0, Line = 0x0, Area = 0x0, Isle = 0x0, n_plines = 0, n_llines = 0, n_blines = 0, n_clines = 0, n_flines = 0, n_klines = 0, n_vfaces = 0, n_hfaces = 0, n_nodes = 0, n_edges = 0, n_lines = 0, n_areas = 0, n_isles = 0, n_faces = 0, n_volumes = 0, n_holes = 0, alloc_nodes = 0, alloc_edges = 0, alloc_lines = 0, alloc_areas = 0, alloc_isles = 0, alloc_faces = 0, alloc_volumes = 0, alloc_holes = 0, Node_offset = 0, Edge_offset = 0, Line_offset = 0, Area_offset = 0, Isle_offset = 0, Volume_offset = 0, Hole_offset = 0, Spidx_built = 0, Spidx_new = 0, Spidx_file = -138544823, spidx_fp = {file = 0x0, start = 0x7ffff7bdf949 <_int_malloc+3465> "\351t\363\377\377H\211\336H\211\357L\213d$(\350\002\340\377\377I\211\307H\205\300u\330\351W\363\377\377H\215=.\225\020", current = 0x0, end = 0x0, size = 0, alloc = 140737349810505, loaded = 32}, Node_spidx_offset = 0, Line_spidx_offset = 3, Area_spidx_offset = 0, Isle_spidx_offset = 80, Face_spidx_offset = 72, Volume_spidx_offset = 206158430213, Hole_spidx_offset = 0, Node_spidx = 0x0, Line_spidx = 0x1, Area_spidx = 0x3100000005, Isle_spidx = 0x0, Face_spidx = 0x0, Volume_spidx = 0x0, Hole_spidx = 0x770000005b, update_cidx = 110, n_cidx = 124, a_cidx = 4702720, cidx = 0x3, cidx_up_to_date = 72, coor_size = -72, coor_mtime = 4703152, uplist = {do_uplist = 1269205248, uplines = 0x7ffff7ab86a8, uplines_offset = 0x7fffffffca58, alloc_uplines = -14336, n_uplines = 32767, upnodes = 0x47c3b0, alloc_upnodes = 4703232, n_upnodes = 0}}, open = -11000, mode = 32767, level = -139753816, head_only = 32767, support_updated = -158932539, name = 0x6 <error: Cannot access memory at address 0x6>, mapset = 0x7fffffffc810 "", location = 0x104d131223011100 <error: Cannot access memory at address 0x104d131223011100>, gisdbase = 0x7fffffffc828 "UNUSED", next_line = 6, constraint = {region_flag = 1398099541, box = {N = 0, S = 6.3659873733898826e-314, E = 6.9533558071306643e-310, W = 1.9762625833649862e-323, T = 6.9913799717015734e-315, B = 0}, type_flag = 2, type = 0, field_flag = -14216, field = 32767}, proj = 6, hist_fp = 0x424952545441, dgraph = {line_type = 0, graph_s = {iErrno = 3, Version = 0 '\000', Endian = 0 '\000', NodeAttrSize = 140737488341152, EdgeAttrSize = 6, aOpaqueSet = {77263313065025, 0, 4, 140737488341192, 5, 323251817538, 0, 5, 140737488341232, 6, 82790901370437, 0, 6, 140737488341272, 6, 75102961091923}, cNode = 0, cHead = 7, cTail = 140737488341312, cAlone = 6, cEdge = 92712327138889, nnCost = 0, Flags = 8, nFamily = 140737488341352, nOptions = 7, pNodeTree = 0x545245534e494d, pEdgeTree = 0x0, pNodeBuffer = 0x9 <error: Cannot access memory at address 0x9>, iNodeBuffer = 140737488341392, pEdgeBuffer = 0x7 <error: Cannot access memory at address 0x7>, iEdgeBuffer = 23734355747555661, edgePrioritizer = {cEdge = 0, iEdge = 0, pEdgePri32Item = 0xa, pvAVL = 0x7fffffffc9b8}, nodePrioritizer = {pvAVL = 0x9}}, spCache = {nStartNode = 3611983955941803350, NodeHeap = {index = 68, count = 11, block = 140737488341472, pnode = 0x9}, pvVisited = 0x3320584554524556, pvPredist = 0x44}, edge_fcosts = 0xc, edge_bcosts = 0x7fffffffca08, node_costs = 0xb, cost_multip = 1414677846}, head = {organization = 0x485345 "", date = 0xd <error: Cannot access memory at address 0xd>, user_name = 0x7fffffffca30 "VERTEX PFACE", map_name = 0xc <error: Cannot access memory at address 0xc>, source_date = 0x5020584554524556 <error: Cannot access memory at address 0x5020584554524556>, orig_scale = 1162035526, comment = 0xe <error: Cannot access memory at address 0xe>, proj = 4695600, plani_zone = 0, digit_thresh = 8.3991159793011913e-323, coor_version = {major = 17, minor = 0, back_major = 0, back_minor = 0}, with_z = 15, size = 140737488341632, head_size = 11, port = {byte_order = 1498173264, off_t_size = 1162758476, dbl_cnvrt = " 2D\000\000\000\000", flt_cnvrt = "\020\000\000", lng_cnvrt = "\000\000\000", int_cnvrt = "\250\312\377\377", shrt_cnvrt = "\377\177", off_t_cnvrt = "\000\000\v\000\000\000\000", dbl_quick = 1498173264, flt_quick = 1162758476, lng_quick = 4469536, int_quick = 0, shrt_quick = 17, off_t_quick = 0}, last_offset = 140737488341712, recycle = 0x3}, dig_fp = {file = 0x435241, start = 0x0, current = 0x12 <error: Cannot access memory at address 0x12>, end = 0x7fffffffcaf8 "CIRCLE", size = 6, alloc = 76193849297219, loaded = -184837864}, fInfo = {i = -186749677, ogr = {driver_name = 0x7fffffffcb20 "LINE", dsn = 0x4 <error: Cannot access memory at address 0x4>, layer_name = 0x454e494c <error: Cannot access memory at address 0x454e494c>, where = 0x44cb10 "\200\313D", driver = 0x479714, ds = 0x47a650, layer = 0x12, dbdriver = 0x12, dsn_options = 0x300000001, layer_options = 0x7ffff4fab415 <H5D_LOPS_COMPACT+85>, cache = {lines = 0x47a670, lines_types = 0x10, lines_cats = 0x10, lines_alloc = 0, lines_num = 0, lines_next = 22, fid = 4695696, sf_type = 17, ctype = 0}, feature_cache = 0x11, offset = {array = 0x0, array_num = 23, array_alloc = 0}, next_line = 4695728}, pg = {conninfo = 0x11 <error: Cannot access memory at address 0x11>, db_name = 0x11 <error: Cannot access memory at address 0x11>, schema_name = 0x0, table_name = 0x18 <error: Cannot access memory at address 0x18>, where = 0x47a6d0 "\232\242G", fid_column = 0x11 <error: Cannot access memory at address 0x11>, geom_column = 0x11 <error: Cannot access memory at address 0x11>, feature_type = SF_GEOMETRY, coor_dim = 0, srid = 25, dbdriver = 0x47a6f0, fi = 0x10, inTransaction = 16, conn = 0x0, res = 0x1a, cursor_name = 0x47a710 "Z\243G", cursor_fid = 18, next_line = 0, cache = {lines = 0x12, lines_types = 0x0, lines_cats = 0x1b, lines_alloc = -13216, lines_num = 32767, lines_next = 5, fid = 362090680144, sf_type = SF_GEOMETRY, ctype = 0}, offset = {array = 0x1c, array_num = -13176, array_alloc = 32767}, topogeom_column = 0x6 <error: Cannot access memory at address 0x6>, toposchema_name = 0x454341464433 <error: Cannot access memory at address 0x454341464433>, toposchema_id = 0, topo_geo_only = 0}}, site_att = 0x1d, n_site_att = -13136, n_site_dbl = 32767, n_site_str = 14}
        n_files = 0
        do_table = 1
        fi_in = 0x0
        fi_out = 0x0
        sql = {string = 0x0, nalloc = 0}
        table_name_in = {string = 0x0, nalloc = 0}
        table_name_out = {string = 0x0, nalloc = 0}
        driver_in = 0x0
        driver_out = 0x0
        table_in = 0x0
        table_out = 0x0
        key = 0x0
        keycol = -1
        maxcat = 0
        out_is_3d = 0
        colnames = '\000' <repeats 3576 times>...
        snap = -1
(gdb)
```

The problem happens in 

https://github.com/OSGeo/grass/blob/61d6f8c7dbddd5a0625970d8a35d78921859201c/lib/db/dbmi_base/table.c#L138

however, probably needs to be already caught in v.patch when (trying to) opening the DB connection (?).
