### ISSUE TITLE
Space character not allowed between topological relations and temporal operator

### ISSUE THREAD

**Issue by NikosAlexandris** [OSGeo/grass#1530]
Given the pattern for temporal selections
```
{"temporal selection operator", "topological relations", "temporal operator"}
```
it seems there is no signle test in https://github.com/OSGeo/grass/blob/99464f8f520a8778564bafa9b2b47bcd8f893bf8/temporal/t.rast.algebra/testsuite/test_raster_algebra.py
that demonstrates an example with a space _after_ the `"topological relations", ` part. All examples in the tests are
(typographically speaking) either
```
{"temporal selection operator","topological relations","temporal operator"}
# no spaces -----------------^^^---------------------^^^
```
or
```
{"temporal selection operator", "topological relations","temporal operator"}
# ----- spaces only here -----^^^ ---but not here ------^^^
```

Adding a space in the last part, causes failures here.
If this is true (and not only something in my system), it is hard to understand and learn why some expressions fail.

_Originally posted by @NikosAlexandris in https://github.com/OSGeo/grass/issues/1528#issuecomment-820451080_

**Comment by NikosAlexandris** [comment]
```
→ t.select expression='test2 = A1 {!:, equal,r} A2'
```
No error. Good.
Then,
```
→ t.select expression='test2 = A1 {!:, equal, r} A2' --o
```
fails
```
Traceback (most recent call last):
  File "/osgeo/grass/dist.x86_64-pc-linux-gnu/scripts/t.select", line 87, in <module>
    sys.exit(main())
  File "/osgeo/grass/dist.x86_64-pc-linux-gnu/scripts/t.select", line 78, in main
    pc = p.parse(expression, stdstype,  overwrite=grass.overwrite())
  File "/osgeo/grass/dist.x86_64-pc-linux-gnu/etc/python/grass/temporal/temporal_algebra.py", line 907, in parse
    self.parser.parse(expression)
  File "/home/nik/code/miniconda3/envs/py385/lib/python3.8/site-packages/ply/yacc.py", line 333, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/home/nik/code/miniconda3/envs/py385/lib/python3.8/site-packages/ply/yacc.py", line 1063, in parseopt_notrack
    lookahead = get_token()     # Get the next token
  File "/home/nik/code/miniconda3/envs/py385/lib/python3.8/site-packages/ply/lex.py", line 386, in token
    newtok = self.lexerrorf(tok)
  File "/osgeo/grass/dist.x86_64-pc-linux-gnu/etc/python/grass/temporal/temporal_algebra.py", line 672, in t_error
    raise SyntaxError("syntax error on line %d position %i near '%s'" %
SyntaxError: syntax error on line 1 position 37 near '{!:, equal, r} A2'
```

**Comment by veroandreo** [comment]
All tests in t.select and t.rast.algebra use the expression with no spaces, so that seems like the safest way to go. However, some commented examples [here](https://github.com/OSGeo/grass/blob/master/python/grass/temporal/temporal_raster_base_algebra.py) use spaces. 

IMHO, if no spaces always works and with spaces, it fails, then we should fix the manual to indicate so. PR's are welcome ;)

The reason for one or the other escapes my understanding, might be just a matter of design or something inherited from lex and yacc libraries...

**Comment by NikosAlexandris** [comment]
> All tests in t.select and t.rast.algebra use the expression with no spaces, so that seems like the safest way to go. However, some commented examples [here](https://github.com/OSGeo/grass/blob/master/python/grass/temporal/temporal_raster_base_algebra.py) use spaces.
> 
> IMHO, if no spaces always works and with spaces, it fails, then we should fix the manual to indicate so. PR's are welcome ;)
> 
> The reason for one or the other escapes my understanding, might be just a matter of design or something inherited from lex and yacc libraries...

I think readability is as important as algorithmic thinking. So a big + from my side to have spaces allowed in the expressions.

**Comment by veroandreo** [comment]
Maybe @huhabla and @m4sth0 can help us here as well
