### ISSUE TITLE
[Bug] Multithreaded r.mapcalc gives "ERROR: Region file user1//WIND is empty".

### ISSUE THREAD

**Issue by Viech** [OSGeo/grass#1614]
**Describe the bug**
I have a Python script that runs  `r.mapcalc` in parallel via `grass.pygrass.modules.interface.module.ParallelModuleQueue`. For a queue size of one (no concurrence) this works fine. For larger numbers (e.g. using all 12 virtual cores of a i7-8700) this can fail arbitrarily with the following traceback:
```
ERROR: Region file user1//WIND is empty
Traceback (most recent call last):
  File "./v.net.evolution.py", line 439, in <module>
    main()
  File "./v.net.evolution.py", line 345, in main
    run_=False,
  File "/usr/lib64/grass78/etc/python/grass/pygrass/modules/interface/module.py", line 248, in put
    self.wait()
  File "/usr/lib64/grass78/etc/python/grass/pygrass/modules/interface/module.py", line 303, in wait
    self._finished_modules.extend([proc.wait(),])
  File "/usr/lib64/grass78/etc/python/grass/pygrass/modules/interface/module.py", line 794, in wait
    module=self.name, errors=stderr)
grass.exceptions.CalledModuleError: Module run r.mapcalc r.mapcalc expression=[...] region=union --o --q ended with error
Process ended with non-zero return code 1. See errors in the (error) output.
```

**To Reproduce**
I can try to build a minimal example if you need one. However as the problem appears to be a race condition related to write access to the region file, it could be hard to reproduce on a machine with less CPU cores or faster filesystem access.

**Expected behavior**
`r.mapcalc` should be thread-safe, assuming the output maps are disjoint.

**System description**
- Operating System: Linux 5.11.6-lp152.4.g7cff707-default x86_64
- GRASS GIS version: 7.8.5
- CPU: Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
```
% g.version -rge
version=7.8.5
date=2020
revision=exported
build_date=2021-05-08
build_platform=x86_64-pc-linux-gnu
build_off_t_size=8
libgis_revision=2021-05-09T13:00:14+00:00
libgis_date=2021-05-09T13:00:14+00:00
proj=7.0.0
gdal=3.2.3
geos=3.9.1
sqlite=3.28.0
% python3 -c "import sys, wx; print(sys.version); print(wx.version())"
3.6.12 (default, Dec 02 2020, 09:44:23) [GCC]
4.0.1 gtk3 (phoenix)
```

**Additional context**
1. The grassdata folder containing the region file is on a networked/remote filesystem.
2. On another workstation with an older i7 (6 virtual cores) and a local filesystem, this problem virtually never occurs.

**Comment by petrasovaa** [comment]
I assume this happens because of r.mapcalc region=union. It seems r.mapcalc in that case writes the region to file:
https://github.com/OSGeo/grass/commit/3bc7d185ce7fc9d8b4e09c5d725f5bf3e0905dfc#diff-4cf2721e9c4808d92465fb6b439c26a05772f6e52e0aafab74e2687c72edc447R859
It shouldn't be doing that. As a workaround for now, I suggest to not use the region parameter.

**Comment by Viech** [comment]
Awesome, this works! I recall that I needed to set the region at some point but now it works fine also without `region=union`.
