### ISSUE TITLE
[Bug] Can't launch any GUI tool from GRASS GIS after wx upgrade (4.1.1)

### ISSUE THREAD

**Issue by saultdon** [OSGeo/grass#1793]
Initial GRASS GUI runs and can open a Location, but trying to run any other window from the top menus like Import Vector Data (v.in.org) fails to launch a window for the tool.

```
Traceback (most recent call last):
  File "/opt/grass/gui/wxpython/lmgr/frame.py", line 929, in
OnMenuCmd

GUI(parent=self, giface=self._giface).ParseCommand(cmd)
  File "/opt/grass/gui/wxpython/gui_core/forms.py", line
2933, in ParseCommand

self.mf = TaskFrame(parent=self.parent, giface=self._giface,
  File "/opt/grass/gui/wxpython/gui_core/forms.py", line
546, in __init__

self.notebookpanel = CmdPanel(
  File "/opt/grass/gui/wxpython/gui_core/forms.py", line
2035, in __init__

win = gselect.GdalSelect(parent=parent, panel=which_panel,
  File "/opt/grass/gui/wxpython/gui_core/gselect.py", line
1520, in __init__

fileFormats = GetFormats(writableOnly=dest)[fType]['file']
  File "/opt/grass/gui/wxpython/core/utils.py", line 713, in
GetFormats

gdalAll, gdalWritable = _getGDALFormats()
  File "/opt/grass/gui/wxpython/core/utils.py", line 645, in
_getGDALFormats

return _parseFormats(ret), _parseFormats(ret,
writableOnly=True)
  File "/opt/grass/gui/wxpython/core/utils.py", line 675, in
_parseFormats

key, name = map(lambda x: x.strip(),
line.strip().rsplit(':', -1))
ValueError
:
too many values to unpack (expected 2)
```

-- OS INFO
```
% uname -a
Linux archasus 5.13.9-arch1-1 #1 SMP PREEMPT Sun, 08 Aug 2021 11:25:35 +0000 x86_64 GNU/Linux
```
-- GRASS INFO
```
% g.version -rge
version=7.8.5
date=2020
revision=exported
build_date=2021-08-11
build_platform=x86_64-pc-linux-gnu
build_off_t_size=8
libgis_revision=2021-08-11T21:29:59+00:00
libgis_date=2021-08-11T01:00:00-07:00
proj=8.1.0
gdal=3.3.1
geos=3.9.1
sqlite=3.36.0
```
-- WX INFO

```
% python3 -c "import sys, wx; print(sys.version); print(wx.version())"
3.9.6 (default, Jun 30 2021, 10:22:16) 
[GCC 11.1.0]
4.1.1 gtk3 (phoenix) wxWidgets 3.1.5
```

Here's some additional info for maybe related issues in dependencies and related GRASS bug.

- https://github.com/wxWidgets/Phoenix/issues/1911
- https://bugs.archlinux.org/task/69393?project=5&string=python-wxpython
- https://github.com/OSGeo/grass/issues/1261

**Comment by saultdon** [comment]
Trying to launch a UI from command line gives a similar error:

```
% v.external --ui
Traceback (most recent call last):
  File "/opt/grass/gui/wxpython/gui_core/forms.py", line 3005, in OnInit
    self.mf = TaskFrame(
  File "/opt/grass/gui/wxpython/gui_core/forms.py", line 546, in __init__
    self.notebookpanel = CmdPanel(
  File "/opt/grass/gui/wxpython/gui_core/forms.py", line 2035, in __init__
    win = gselect.GdalSelect(parent=parent, panel=which_panel,
  File "/opt/grass/gui/wxpython/gui_core/gselect.py", line 1520, in __init__
    fileFormats = GetFormats(writableOnly=dest)[fType]['file']
  File "/opt/grass/gui/wxpython/core/utils.py", line 713, in GetFormats
    gdalAll, gdalWritable = _getGDALFormats()
  File "/opt/grass/gui/wxpython/core/utils.py", line 645, in _getGDALFormats
    return _parseFormats(ret), _parseFormats(ret, writableOnly=True)
  File "/opt/grass/gui/wxpython/core/utils.py", line 675, in _parseFormats
    key, name = map(lambda x: x.strip(), line.strip().rsplit(':', -1))
ValueError: too many values to unpack (expected 2)
OnInit returned false, exiting...
```

**Comment by tmszi** [comment]
I tried to reproduce it and in dev  version 7.8.6 (Git branch [releasebranch_7_8](https://github.com/OSGeo/grass/tree/releasebranch_7_8)) it is already fixed.

```
GRASS 7.8.6dev (nc_basic_spm_grass7):~ > python -c "import sys, wx; print(sys.version); print(wx.version())"
3.9.6 (default, Aug  8 2021, 07:26:00) 
[GCC 10.3.0]
4.1.1 gtk3 (phoenix) wxWidgets 3.1.5
```

```
GRASS 7.8.6dev (nc_basic_spm_grass7):~ > g.version -rge
version=7.8.6dev
date=2021
revision=7dbec1783
build_date=2021-08-19
build_platform=x86_64-pc-linux-gnu
build_off_t_size=8
libgis_revision=7dbec1783
libgis_date=2021-08-10T12:45:14+00:00
proj=7.2.1
gdal=3.2.2
geos=3.9.1
sqlite=3.35.5
```

**Comment by saultdon** [comment]
Awesome, it sure is!

```
% python -c "import sys, wx; print(sys.version); print(wx.version())"
3.9.6 (default, Jun 30 2021, 10:22:16) 
[GCC 11.1.0]
4.1.1 gtk3 (phoenix) wxWidgets 3.1.5
```

```
% g.version -rge
version=7.8.6dev
date=2021
revision=exported
build_date=2021-08-22
build_platform=x86_64-pc-linux-gnu
build_off_t_size=8
libgis_revision=2021-08-22T02:20:25+00:00
libgis_date=2021-08-21T01:00:00-07:00
proj=8.1.0
gdal=3.3.1
geos=3.9.1
sqlite=3.36.0
```
