### ISSUE TITLE
[Bug] Grass 7.8.5-1 (GNU/Debian) Some tools (v.import; v.in.ogr; r.import) do not start on GUI

### ISSUE THREAD

**Issue by tomassenabre** [OSGeo/grass#1968]
**Describe the bug**
I have a stable GNU / Debian 11 installation (Bullseye), and I have installed Grass from the repositories, version 7.8.5-1, but the layer import tools do not work from the GUI. 

**To Reproduce**
Just launch these tools from the GUI or from command console. I get errors in the console like this:

```
GRASS 7.8.5 (Almeria_ETRS89):/media/SIG/grassdata > v.in.ogr
Traceback (most recent call last):
  File "/usr/lib/grass78/gui/wxpython/gui_core/forms.py", line 3005, in OnInit
    self.mf = TaskFrame(
  File "/usr/lib/grass78/gui/wxpython/gui_core/forms.py", line 546, in __init__
    self.notebookpanel = CmdPanel(
  File "/usr/lib/grass78/gui/wxpython/gui_core/forms.py", line 2035, in __init__
    win = gselect.GdalSelect(parent=parent, panel=which_panel,
  File "/usr/lib/grass78/gui/wxpython/gui_core/gselect.py", line 1520, in __init__
    fileFormats = GetFormats(writableOnly=dest)[fType]['file']
  File "/usr/lib/grass78/gui/wxpython/core/utils.py", line 713, in GetFormats
    gdalAll, gdalWritable = _getGDALFormats()
  File "/usr/lib/grass78/gui/wxpython/core/utils.py", line 645, in _getGDALFormats
    return _parseFormats(ret), _parseFormats(ret, writableOnly=True)
  File "/usr/lib/grass78/gui/wxpython/core/utils.py", line 675, in _parseFormats
    key, name = map(lambda x: x.strip(), line.strip().rsplit(':', -1))
ValueError: too many values to unpack (expected 2)
OnInit returned false, exiting...
``` 

**Expected behavior**

**Screenshots**

**System description (please complete the following information):**

- Operating System: GNU/Debian Ver. 11. Bullseye 
- GRASS GIS version [7.8.5-1] (https://packages.debian.org/bullseye/grass)

**Additional context**

**Comment by veroandreo** [comment]
Would you try `v.in.ogr --ui`? When calling the gui of v.in.ogr, v.import or r.import without parameters in grass 7.8.5 - fedora 34, I get the summary manual in the console... In grass 8.0 - main branch, typing v.in.ogr in the terminal opens the gui directly as expected.

Also, is it possible for you to update to the latest grass 7.8.6 and check if the problem persists also there?

**Comment by petrasovaa** [comment]
Should be fixed in 7.8.6:  #1793

**Comment by tomassenabre** [comment]
Hello and thanks for your answers. I have followed the steps to compile Grass from source and I must have done something unconsciously because I installed version 8 of Grass! I hope I don't have many problems with the development version.
All modules are working properly again, but right now Debian users install an unusable version of Grass since they cannot import layers.
