### ISSUE TITLE
[Bug] You probably called setlocale() directly instead of using wxLocale and now there is a mismatch between C/C++ and Windows locale.

### ISSUE THREAD

**Issue by bwegsche** [OSGeo/grass#2001]
Hi everyone,
I'm quite new to grass and I run into problems loading the GUI.
I get following error message, hopefully someone can point me in the right direction to solve the problem.
Thanks

C:\Users\bwegsche>Traceback (most recent call last):
  File "C:\Program Files\GRASS GIS 7.8\gui\wxpython\wxgui.py", line 105, in OnInit
    mainframe = GMFrame(parent=None, id=wx.ID_ANY,
  File "C:\Program Files\GRASS GIS 7.8\gui\wxpython\lmgr\frame.py", line 141, in __init__
    self._createMenuBar()
  File "C:\Program Files\GRASS GIS 7.8\gui\wxpython\lmgr\frame.py", line 268, in _createMenuBar
    self.menubar = GMenu(
  File "C:\Program Files\GRASS GIS 7.8\gui\wxpython\gui_core\menu.py", line 47, in __init__
    self.Append(self._createMenu(child), child.label)
  File "C:\Program Files\GRASS GIS 7.8\gui\wxpython\gui_core\menu.py", line 61, in _createMenu
    self._createMenuItem(menu, label=child.label, **data)
  File "C:\Program Files\GRASS GIS 7.8\gui\wxpython\gui_core\menu.py", line 88, in _createMenuItem
    menuItem.SetBitmap(MetaIcon(img=icon).GetBitmap(self.bmpsize))
  File "C:\Program Files\GRASS GIS 7.8\gui\wxpython\icons\icon.py", line 96, in GetBitmap
    image = wx.Image(name=self.imagepath)
wx._core.wxAssertionError: C++ assertion "strcmp(setlocale(0, 0), "C") == 0" failed at D:\src\osgeo4w\src\wxwidgets\wxwidgets-3.1.5-0df1d81acd6f1be8624022f8eecb51679008ca40\src\common\intl.cpp(1694) in wxLocale::GetInfo(): You probably called setlocale() directly instead of using wxLocale and now there is a mismatch between C/C++ and Windows locale.
Things are going to break, please only change locale by creating wxLocale objects to avoid this!
OnInit returned false, exiting...

**Comment by hellik** [comment]
do you have more than one python on %PATH% ?

**Comment by hellik** [comment]
`"C:\Program Files\GRASS GIS 7.8\gui\wxpython\wxgui.py"`

vs.

 `D:\src\osgeo4w\src\wxwidgets\wxwidgets-3.1.5-0df1d81acd6f1be8624022f8eecb51679008ca40\src\common\intl.cpp(1694)`

**Comment by hellik** [comment]
is this `GRASS GIS 7.8.6` ?

**Comment by bwegsche** [comment]
Hi hellik,

Thanks for your response.
Yes, I`m using GRASS GIS 7.8.6

I have python 2.7 installed to run ArcGIS 10.8 
I assume your comment suggests that python 2.7 might not be compatible with the news version of GRASS GIS?

I now installed an older version of GRASS GIS (7.6) and now the GUI is loading correctly.
Is it possible though to also install a new version of python and be able to run both ArcGIS and GRASS GIS with the most up to date version?

Thanks for the help,
Bernhard

**Comment by hellik** [comment]
>I assume your comment suggests that python 2.7 might not be compatible with the news version of GRASS GIS?

yes. 

IIRC, in GRASS GIS 7.8.x we switched to python 3 at some point.

actually, we're shipping winGRASS 7.8.6 with:

```
GRASS Version: 7.8.6                                                            
Code revision: exported                                                         
Build date: 2021-11-11                                                          
Build platform: x86_64-w64-mingw32                                              
GDAL: 3.4.0                                                                     
PROJ: 8.2.0                                                                     
GEOS: 3.10.0                                                                    
SQLite: 3.35.2                                                                  
Python: 3.9.5             <=                                                      
wxPython: 4.1.1                                                                 
Platform: Windows-10-10.0.19044-SP0 (OSGeo4W)
```

AFAIK, most of/all linux distributions switched to python 3 too.

see [GRASS 7.8.0 news](https://grass.osgeo.org/news/2019_09_15_grass_gis_7_8_0_released/)

`Efforts have concentrated on implementing Python 3 support.`

python 3 is definitely the way to go with the newest (win)GRASS GIS versions.

**Comment by neteler** [comment]
> Thanks for your response. Yes, I`m using GRASS GIS 7.8.6
> 
> I have python 2.7 installed to run ArcGIS 10.8 

Some background info why we switched to Python 3:

Please note that Python 2 went end-of-life 
https://www.python.org/doc/sunset-python-2/

_As of January 1st, 2020 no new bug reports, fixes, or changes will be made to Python 2, and Python 2 is no longer supported._

Hence our (meanwhile completed) efforts to update GRASS GIS for Python 3.

**Comment by neteler** [comment]
Looks like working... Closing.

**Comment by bwegsche** [comment]
Yes thanks a lot. I`m using now GRASS 7.6 which works fine.

Thanks for the help!

**Comment by nilason** [comment]
I believe #2101 is reporting the same issue as this.

**Comment by franzzoa** [comment]
> Yes thanks a lot. I`m using now GRASS 7.6 which works fine.
> 
> Thanks for the help!

I am using the latest versio of Grass GIS (8) and I have installed python version 3.8 and I am having the same issue. Can someone help out? Other solutions proposed setting a global variable to hold a specific local self.locale = wx.Locale(language=wx.LANGUAGE_ENGLISH). But this is not working either.
