### ISSUE TITLE
[Bug] GRASS 78 needs subversion for addons installation

### ISSUE THREAD

**Issue by afrigeri** [OSGeo/grass#2293]
**Describe the bug**

From a fresh ubuntu install, we have installed Grass78 and started to use it.

**To Reproduce**

1. g.extension extension=v.centerline 
2. error.. svn not found!
```
g.extension extension=v.centerline                                              
Fetching <v.centerline> from GRASS GIS Addons repository (be patient)...
Traceback (most recent call last):
  File "/usr/lib/grass78/scripts/g.extension", line 2350, in
<module>
    sys.exit(main())
  File "/usr/lib/grass78/scripts/g.extension", line 2330, in
main
    install_extension(source=source, url=url, xmlurl=xmlurl,
branch=branch)
  File "/usr/lib/grass78/scripts/g.extension", line 873, in
install_extension
    ret1, new_modules_ext, new_files_ext, tmp_dir =
install_extension_std_platforms(extension,
  File "/usr/lib/grass78/scripts/g.extension", line 1523, in
install_extension_std_platforms
    download_source_code(source=source, url=url, name=name,
  File "/usr/lib/grass78/scripts/g.extension", line 1454, in
download_source_code
    download_source_code_official_github(url, name, outdev,
directory)
  File "/usr/lib/grass78/scripts/g.extension", line 1336, in
download_source_code_official_github
    if grass.call(['svn', 'export',
  File "/usr/lib/grass78/etc/python/grass/script/core.py",
line 74, in call
    return Popen(*args, **kwargs).wait()
  File "/usr/lib/grass78/etc/python/grass/script/core.py",
line 63, in __init__
    subprocess.Popen.__init__(self, args, **kwargs)
  File "/usr/lib/python3.9/subprocess.py", line 951, in
__init__
    self._execute_child(args, executable, preexec_fn,
close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1821, in
_execute_child
    raise child_exception_type(errno_num, err_msg,
err_filename)
FileNotFoundError: [Errno 2] No such file or directory:
'svn'
(Mon Apr  4 11:42:22 2022) Command finished (1 sec)  

```

**Expected behavior**
having the addon installed

**Screenshots**
not needed

**Solution**

After installing subversion package, the FileNotFoundError disappears, but a new issue comes up: 
```
g.extension v.centerline
Fetching <v.centerline> from GRASS GIS Addons repository (be patient)...
svn: E170000: URL 'https://github.com/OSGeo/grass-addons/trunk/grass7/vector/v.centerline' doesn't exist
ERROR: GRASS Addons <v.centerline> not found
```
the addon is not found.

The solution has been to clone the addons locally and then:

```
g.extension v.centerline url=/PATH_TO/grass-addons/src/vector/v.centerline
...
Installation of <v.centerline> successfully finished
```

**System description (please complete the following information):**

- Operating System:  Ubuntu 21.10
- GRASS GIS version  GRASS 7.8.5

**Additional context**

**Comment by neteler** [comment]
The test has been already added in Dec 2020:

- g.extension: check if svn program is installed #1145 

and backported to GRASS 7.8.6 as part of #1762.

Please update your installation.
