### ISSUE TITLE
WinGRASS standlone installer is compiled with errors

### ISSUE THREAD

**Issue by tmszi** [OSGeo/grass#2497]
**Describe the bug**
WinGRASS standalone installer is compiled with errors.

**To Reproduce**

1. Install [WinGRASS-8.3.dev-56986425a-1-Setup.exe standalone installer](https://wingrass.fsv.cvut.cz/grass83/WinGRASS-8.3.dev-56986425a-1-Setup.exe).
2. Launch GRASS GIS 
3. See error
```
Launching <wxpython> GUI in the background, please wait...
Microsoft Windows [Version 10.0.17763.1935]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\Users\IEUser>wxdigit.py: Could not load grass_vector.8.3.
wxdigit.py: Could not load grass_vector.8.3.
wxnviz.py: Could not load grass_g3d.8.3.
Traceback (most recent call last):
  File "C:\Program Files\GRASS GIS 8.3\Python39\lib\site-packages\wx\core.py", line 3407, in <lambda>
    lambda event: event.callable(*event.args, **event.kw) )
  File "C:\Program Files\GRASS GIS 8.3\gui\wxpython\wxgui.py", line 95, in show_main_gui
    mainframe = GMFrame(parent=None, id=wx.ID_ANY, workspace=self.workspaceFile)
  File "C:\Program Files\GRASS GIS 8.3\gui\wxpython\main_window\frame.py", line 164, in __init__
    self.BuildPanes()
  File "C:\Program Files\GRASS GIS 8.3\gui\wxpython\main_window\frame.py", line 533, in BuildPanes
    self.statusbar = SbMain(parent=self, giface=self._giface)
  File "C:\Program Files\GRASS GIS 8.3\gui\wxpython\lmgr\statusbar.py", line 38, in __init__
    self.mask = SbMask(self.widget, self.giface)
  File "C:\Program Files\GRASS GIS 8.3\gui\wxpython\lmgr\statusbar.py", line 87, in __init__
    self.Refresh()
  File "C:\Program Files\GRASS GIS 8.3\gui\wxpython\lmgr\statusbar.py", line 120, in Refresh
    if gs.find_file(
KeyError: 'name'
```
4. Affected is compilation process of WinGRASS Addons ([some addons](https://github.com/OSGeo/grass/issues/2288#issuecomment-1193299774)) on our osgeo server too
4. Full WinGRASS [compilation log](https://wingrass.fsv.cvut.cz/grass82/logs/log-rc6e80e6f4-1/package.log).
5. Full WinGRASS [error log](https://wingrass.fsv.cvut.cz/grass82/logs/log-rc6e80e6f4-1/error.log).

**Expected behavior**
WinGRASS standalone installer should be compiled without errors and affected WinGRASS Addons should be compiled without errors on our osgeo server too.

**System description (please complete the following information):**

- Operating System: MS Windows
- GRASS GIS version: 8.3.dev, 8.2

**Additional context**
Issue is analyzed here https://github.com/OSGeo/grass/issues/2288#issuecomment-1194101047.

**Comment by petrasovaa** [comment]
I wonder if this is still a problem?

**Comment by tmszi** [comment]
But under GRASS GIS **8.2 version** issue still persist. Check the i.destripe addon [compilation log](url) on MS Windows OS from the Mon, 25 Sep 2023 15:03:38, please.

**Comment by petrasovaa** [comment]
Right, 8.2.1 addons are not properly compiled. It is unlikely though this will get fixed any time soon.

**Comment by wenzeslaus** [comment]
From my perspective, no need to keep this open.

With 8.3.0 released, we don't support 8.2 series - or something like that. We don't have a clear policy which would specifically cover what we do for addons on Windows for older releases. The general policy is that we (collectively as project) do not support older releases, but that individual contributors can choose support legacy releases (e.g., a company for their customers). In that cases, we (collectively as project) support these individual contributors in doing that (by having right backport labels, entry on the website, etc.). I'm afraid we don't have this in any guideline yet, but it might be in some PSC minutes.
