### ISSUE TITLE
[Bug] python script.setup issues related to message translation

### ISSUE THREAD

**Issue by tpilz** [OSGeo/grass#2515]
**Describe the bug**

I want to use GRASS in a python module but get some errors when using certain functions of the `grass.script.setup` module.

**To Reproduce**

Connect to a grass mapset in python as described in the [docs](https://grass.osgeo.org/grass82/manuals/libpython/script.html#module-script.setup), e.g.

```python
import grass.script.setup as gsetup
rcfile = gsetup.init('my_db', 'my_location', 'my_mapset')
rcfile.finish()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/grass82/etc/python/grass/script/setup.py", line 415, in finish
    finish()
  File "/usr/local/grass82/etc/python/grass/script/setup.py", line 474, in finish
    clean_default_db()
  File "/usr/local/grass82/etc/python/grass/script/setup.py", line 434, in clean_default_db
    gcore.message(_("Cleaning up default sqlite database ..."))
TypeError: 'str' object is not callable
```

**System description (please complete the following information):**

Tested on two Linux systems with GRASS 7.8 and GRASS 8.2 using python 3.6.2 and 3.9.10, respectively.

**Additional context**

Error is caused by ` gcore.message(_("<message>"))` calls in `setup.py`. I think #551 is related where the issue was discussed but never really solved.

For the time being a workaround works for my case with `gutils.try_remove(os.environ["GISRC"])` which is basically what I need here.

**Comment by tpilz** [comment]
Thanks for the explanation and workaround!

I was actually using and initialising GRASS inside a python module and got the error when using that. Can't tell which other side-effects then might have caused the interference with the `_` variable.

Anyway, my small workaround is sufficient now and it seems it is even not too complicated to fix it in GRASS.

**Comment by wenzeslaus** [comment]
> ...which other side-effects then might have caused the interference with the `_` variable.

doctest are using `_` and definitively interfere too, although there is a workaround for that too, search for "doctest workaround" in GRASS GIS source code. Running your code through an execute function in an IDE may run run it in an interactive console, too.

> ...it seems it is even not too complicated to fix it in GRASS.

Yes, there is a lot of other pieces in place making the change easier than it was in the past (one place for initialization, lazy loading, code checks). I would be happy to review a PR for this.

**Comment by wenzeslaus** [comment]
There was no PR to change how the translate function is handled, although since then, the issue was mitigated by less verbosity and less translatable messages for errors. The specific issue reported here still persist, so I'm leaving this open as valid.

I'm afraid we can't fix that before 8.5 which should come soon, but it would be great to have it done before 8.6 in spring.
