### ISSUE TITLE
[Bug] Attribute Table Manager fails with TEXT data column containing newline

### ISSUE THREAD

**Issue by nilason** [OSGeo/grass#2635]
**Describe the bug**

Attempt to open Attribute Table Manager for a layer with TEXT data column containing newline throws an exception:

```
Error
Unable to read the table <blobtest> from the database due to seemingly inconsistent number of columns in the data transfer. Check row: "a": "10",... Likely, a newline character is present in the attribute value starting with: '"a": "10",' Use the v.db.select module to investigate.

Reason: Unable to read the table <blobtest> from the database due to seemingly inconsistent number of columns in the data transfer. Check row: "a": "10",... Likely, a newline character is present in the attribute value starting with: '"a": "10",' Use the v.db.select module to investigate.

Traceback (most recent call last):
File "/dev/grass/dist.aarch64-apple-darwin21.6.0/gui/wxpython/dbmgr/base.py", line 129, in __init__
keyColumn = self.LoadData(layer)
File "/dev/grass/dist.aarch64-apple-darwin21.6.0/gui/wxpython/dbmgr/base.py", line 325, in LoadData
raise GException(
core.gcmd.GException: Unable to read the table <blobtest> from the database due to seemingly inconsistent number of columns in the data transfer. Check row: "a": "10",... Likely, a newline character is present in the attribute value starting with: '"a": "10",' Use the v.db.select module to investigate.

```

The data table:
```
v.db.select  blobtest
cat|ID_int32|ID_int64|date_time|json
1|1|20|2022-11-16 00:00:00|{
    "a": "10",
    "b": "20",
    "c": "30"
}

db.describe blobtest
...
column:json
description:
type:TEXT
len:1000
scale:0
precision:0
default:
nullok:yes
select:?
update:?
```

**To Reproduce**

1. Using #2630
2. Import data, see https://github.com/OSGeo/grass/issues/2628#issuecomment-1304619072
3. In GUI, choose "Show Attribute data" in Layers panel.

**Expected behavior**
Attribute table should open without exception.
Possible solution for the TEXT fields:
a) Non-editable with a eg. '\<TEXT\>' stand-in displayed.
b) Contains button which opens a mini text edit window, enabling editing and or viewing.

**System description (please complete the following information):**

- Operating System: all
- GRASS GIS version 8

**Comment by marisn** [comment]
This is not the only place where code fails on a newline: #2576

**Comment by ninsbl** [comment]
Note: The column "json" was created to test support for JSON data in SQLite. JSON-support in SQLite has recently been further improved:
https://tirkarthi.github.io/programming/2022/02/26/sqlite-json-improvements.html
