### ISSUE TITLE
[Bug] GRASS 8.2.0 crashes at startup - Rect.SetHeight(): argument 1 has unexpected type 'float'

### ISSUE THREAD

**Issue by mapperfr** [OSGeo/grass#2690]
**Describe the bug**

GRASS doesn't launch and the terminal displays a Python error.

1. Open a terminal 
2. Type grass and Enter

OR

1. Launch GRASS from desktop icon
2. See error!

**Expected behavior**

GRASS should launch.

**Screenshots**

Here's the full error log:

```
GRASS tmploc/PERMANENT:~ > /usr/lib/grass82/scripts/g.extension:167: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  from distutils.dir_util import copy_tree
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/wx/core.py", line 3282, in <lambda>
    lambda event: event.callable(*event.args, **event.kw) )
  File "/usr/lib/grass82/gui/wxpython/wxgui.py", line 95, in show_main_gui
    mainframe = GMFrame(parent=None, id=wx.ID_ANY, workspace=self.workspaceFile)
  File "/usr/lib/grass82/gui/wxpython/main_window/frame.py", line 164, in __init__
    self.BuildPanes()
  File "/usr/lib/grass82/gui/wxpython/main_window/frame.py", line 645, in BuildPanes
    self._auimgr.AddPane(
  File "/usr/lib/python3/dist-packages/wx/lib/agw/aui/framemanager.py", line 4711, in AddPane
    return self.AddPane4(window, arg1, target)
  File "/usr/lib/python3/dist-packages/wx/lib/agw/aui/framemanager.py", line 4879, in AddPane4
    self.UpdateNotebook()
  File "/usr/lib/python3/dist-packages/wx/lib/agw/aui/framemanager.py", line 6653, in UpdateNotebook
    notebook.AddPage(pane.window, title, True, pane.icon)
  File "/usr/lib/python3/dist-packages/wx/lib/agw/aui/auibook.py", line 3575, in AddPage
    return self.InsertPage(self.GetPageCount(), page, caption, select, bitmap, disabled_bitmap, control, tooltip)
  File "/usr/lib/python3/dist-packages/wx/lib/agw/aui/auibook.py", line 3653, in InsertPage
    self.SetSelectionToWindow(page)
  File "/usr/lib/python3/dist-packages/wx/lib/agw/aui/auibook.py", line 4410, in SetSelectionToWindow
    self.SetSelection(idx)
  File "/usr/lib/python3/dist-packages/wx/lib/agw/aui/auibook.py", line 4357, in SetSelection
    ctrl.MakeTabVisible(ctrl_idx, ctrl)
  File "/usr/lib/python3/dist-packages/wx/lib/agw/aui/auibook.py", line 1843, in MakeTabVisible
    if not self.IsTabVisible(tabPage, self.GetTabOffset(), dc, win):
  File "/usr/lib/python3/dist-packages/wx/lib/agw/aui/auibook.py", line 1732, in IsTabVisible
    self.Render(dc, wnd)
  File "/usr/lib/python3/dist-packages/wx/lib/agw/aui/auibook.py", line 1687, in Render
    page.rect, tab_button.rect, x_extent = self._art.DrawTab(dc, wnd, page, rect, tab_button.cur_state)
  File "/usr/lib/python3/dist-packages/wx/lib/agw/aui/tabart.py", line 475, in DrawTab
    r.SetHeight(r.GetHeight()/2)
TypeError: Rect.SetHeight(): argument 1 has unexpected type 'float'
```

**System description (please complete the following information):**

- Operating System: Ubuntu 22.10 Wayland
- GRASS GIS version 8.2.0

- details about further software components
    - run `g.version -rge` in a GRASS GIS terminal session or check in
      the GUI menu "Help > About"
       
      (can't)

    - run `python3 -c "import sys, wx; print(sys.version); print(wx.version())"`
      to print the Python and wxPython version numbers

        Python 3.10.7 (main, Nov 24 2022, 19:45:47) [GCC 12.2.0]
        wxPython 4.0.7 gtk3 (phoenix) wxWidgets 3.0.5

**Comment by tmszi** [comment]
It is wxPython 4.0.7 gtk3 (phoenix) wxWidgets 3.0.5 version bug due Python 3.10.7 version (with Python 3.9.15 wxPython 4.0.7 version works correctly)

Solution:

Install **wxPython 4.2.0** gtk3 (phoenix) wxWidgets 3.2.0 version via Python Pip package manager.

Uninstall default wxPython 4.0.7 package:

`sudo apt remove python3-wxgtk4.0`

or 

use Python virtual environment:

`python3 -m venv $HOME/wxpy42 && source $HOME/wxpy42/bin/activate`

`pip install wxPython` (require compilation tools and wxPython dev dependencies installed, compilation take times)

For GNU/Linux **Ubuntu 22.04.1 LTS (Jammy Jellyfish)** is created binary wxPython 4.2.0 version wheel package installed by Python Pip package manager.

```
pip install -U \
-f https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-22.04 \
wxPython
```
