### ISSUE TITLE
GUI error

### ISSUE THREAD

**Issue by FMestre1** [OSGeo/grass#2745]
I installed GRASS from WinGRASS-8.2.1RC1-1-Setup.exe on a computer running Windows 11 Pro. Apparently, the install went well, but there is an error loading the GUI (I tried installing other versions with roughly the same results, I guess this might have something to do with my computer):

C:\Users\FMest>Traceback (most recent call last):
  File "C:\Program Files\GRASS GIS 8.2\Python39\lib\site-packages\wx\core.py", line 3427, in <lambda>
    lambda event: event.callable(*event.args, **event.kw) )
  File "C:\Program Files\GRASS GIS 8.2\gui\wxpython\wxgui.py", line 95, in show_main_gui
    mainframe = GMFrame(parent=None, id=wx.ID_ANY, workspace=self.workspaceFile)
  File "C:\Program Files\GRASS GIS 8.2\gui\wxpython\lmgr\frame.py", line 156, in __init__
    self.statusbar = SbMain(parent=self, giface=self._giface)
  File "C:\Program Files\GRASS GIS 8.2\gui\wxpython\lmgr\statusbar.py", line 38, in __init__
    self.mask = SbMask(self.widget, self.giface)
  File "C:\Program Files\GRASS GIS 8.2\gui\wxpython\lmgr\statusbar.py", line 87, in __init__
    self.Refresh()
  File "C:\Program Files\GRASS GIS 8.2\gui\wxpython\lmgr\statusbar.py", line 120, in Refresh
    if gs.find_file(
KeyError: 'name'

**Comment by petrasovaa** [comment]
What do you get when you execute this in the black terminal?

`g.findfile -n element=cell file=MASK`

**Comment by FMestre1** [comment]
I get an error message "Entry point not found": Could not find procedure entry point opj_encoder_set_extra_options in DLL (dynamic-link library): C:\Program Files\GRASS GIS 8.2\extrabin\gdal306.dll.

**Comment by hellik** [comment]
> I get an error message "Entry point not found": Could not find procedure entry point opj_encoder_set_extra_options in DLL (dynamic-link library): C:\Program Files\GRASS GIS 8.2\extrabin\gdal306.dll.

It looks like dependency DLL mismatch.

@landam could you check and update the dependencies?

**Comment by hellik** [comment]
> > I get an error message "Entry point not found": Could not find procedure entry point opj_encoder_set_extra_options in DLL (dynamic-link library): C:\Program Files\GRASS GIS 8.2\extrabin\gdal306.dll.
> 
> It looks like dependency DLL mismatch.
> 
> @landam could you check and update the dependencies?

It may be something around OpenJPEG lib.

**Comment by tmszi** [comment]
Same issue as #2497 and error still persists.

**Comment by neteler** [comment]
We got the same error on Linux Mint (repo: https://launchpad.net/~ubuntugis/+archive/ubuntu/ubuntugis-unstable)

```
python --version
Python 3.10.12

grass
Starting GRASS GIS...

          __________  ___   __________    _______________
         / ____/ __ \/   | / ___/ ___/   / ____/  _/ ___/
        / / __/ /_/ / /| | \__ \\_  \   / / __ / / \__ \
       / /_/ / _, _/ ___ |___/ /__/ /  / /_/ // / ___/ /
       \____/_/ |_/_/  |_/____/____/   \____/___//____/

Welcome to GRASS GIS 8.3.2
GRASS GIS Webseite                       https://grass.osgeo.org
This version running through:            Bash Shell (/bin/bash)
Help is available with the command:      g.manual -i
See the licence terms with:              g.version -c
See citation options with:               g.version -x
If required, restart the GUI with:       g.gui wxpython
When ready to quit enter:                exit

Starte <wxpython> GUI im Hintergrund. Bitte warten Sie ...
GRASS world_latlong_wgs84/PERMANENT:~ > Traceback (most recent call last):
  File "/home/pheid/.local/lib/python3.10/site-packages/wx/core.py", line 3427, in <lambda>
    lambda event: event.callable(*event.args, **event.kw) )
  File "/usr/lib/grass83/gui/wxpython/wxgui.py", line 95, in show_main_gui
    mainframe = GMFrame(
  File "/usr/lib/grass83/gui/wxpython/main_window/frame.py", line 177, in __init__
    self.BuildPanes()
  File "/usr/lib/grass83/gui/wxpython/main_window/frame.py", line 563, in BuildPanes
    self.statusbar = SbMain(parent=self, giface=self._giface)
  File "/usr/lib/grass83/gui/wxpython/lmgr/statusbar.py", line 38, in __init__
    self.mask = SbMask(self.widget, self.giface)
  File "/usr/lib/grass83/gui/wxpython/lmgr/statusbar.py", line 87, in __init__
    self.Refresh()
  File "/usr/lib/grass83/gui/wxpython/lmgr/statusbar.py", line 120, in Refresh
    if gs.find_file(
KeyError: 'name'
```

Checking `g.findfile`:

```
GRASS world_latlong_wgs84/PERMANENT:~ > g.findfile -n element=cell file=MASK
name=
mapset=
fullname=
file=
Speicherzugriffsfehler (Speicherabzug geschrieben)
```
(-> segmentation fault)

`strace` to see some details:
```
GRASS world_latlong_wgs84/PERMANENT:~ > strace g.findfile -n element=cell file=MASK
execve("/usr/lib/grass83/bin/g.findfile", ["g.findfile", "-n", "element=cell", "file=MASK"], 0x7ffccbc963d8 /* 78 vars */) = 0
brk(NULL)                               = 0x5599e3c39000
...

access("/home/pheid/grassdata/world_latlong_wgs84", F_OK) = 0
newfstatat(AT_FDCWD, "/home/pheid/grassdata/world_latlong_wgs84/PERMANENT", {st_mode=S_IFDIR|0755, st_size=4096, ...}, 0) = 0
getuid()                                = 1001
geteuid()                               = 1001
access("/home/pheid/grassdata/world_latlong_wgs84/PERMANENT/SEARCH_PATH", F_OK) = -1 ENOENT (Datei oder Verzeichnis nicht gefunden)
access("/home/pheid/grassdata/world_latlong_wgs84/PERMANENT/cellhd/MASK", F_OK) = -1 ENOENT (Datei oder Verzeichnis nicht gefunden)
newfstatat(1, "", {st_mode=S_IFCHR|0620, st_rdev=makedev(0x88, 0x1), ...}, AT_EMPTY_PATH) = 0
write(1, "name=\n", 6name=
)                  = 6
write(1, "mapset=\n", 8mapset=
)                = 8
write(1, "fullname=\n", 10fullname=
)             = 10
write(1, "file=\n", 6file=
)                  = 6
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x559cba56e093} ---
+++ killed by SIGSEGV (core dumped) +++
Speicherzugriffsfehler (Speicherabzug geschrieben)
```

**Comment by marisn** [comment]
For a segfault GDB backtrace is more useful. Still I would start by checking if there are no multiple versions of GDAL, PROJ and GRASS has been recompiled / linked with the actual versions in the system.

**Comment by neteler** [comment]
Since it is a Ubuntu provided package, debugging is AFAIK less easy.

Using `valgrind`

```
CMD="g.findfile -n element=cell file=MASK"
valgrind --tool=memcheck --log-file=/tmp/valgrind_out.log $CMD
```

showed that a duplicate PROJ installation had happened. Cleaning the mess up solved the problem.
