### ISSUE TITLE
[Bug] Space in paths fails on creation a space with python bindings

### ISSUE THREAD

**Issue by latot** [OSGeo/grass#3041]
**Describe the bug**
Seems there is missing some ```"``` in the paths with parsing then to grass. 

Is it possible to other sections, to have missed this, not just the create case.

**To Reproduce**
```bash
mkdir /tmp/"a b"
```

```
from grass_session import Session

mygisdb = "/tmp/a b"
mylocation = 'world'

PERMANENT = Session()
PERMANENT.open(
  gisdb=mygisdb,
  location=mylocation,
  create_opts='EPSG:3857'
)
PERMANENT.close()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/pyenv/lib/python3.10/site-packages/grass_session/session.py", line 450, in open
    self.create(path, create_opts=create_opts)
  File "/home/user/pyenv/lib/python3.10/site-packages/grass_session/session.py", line 468, in create
    grass_create(self.grassbin, path, create_opts)
  File "/home/user/pyenv/lib/python3.10/site-packages/grass_session/session.py", line 322, in grass_create
    raise RuntimeError(
RuntimeError: Cannot create: /tmp/a b/world with the following options: EPSG:3857. Executing:
grass -c EPSG:3857 -e /tmp/a b/world
GRASS said:
b''
b'usage: grass [-h] [-v] [--text] [--gtext] [--gui] [-c [CRS]] [-e]\n             [--config [CONFIG ...]] [--tmp-mapset] [--tmp-location CRS] [-f]\n             [--exec ...]\n             [PATH]\ngrass: error: unrecognized arguments: b/world\n'
```
**Expected behavior**
Create the db.

**System description (please complete the following information):**

- Operating System: Linux Gentoo 64
- GRASS GIS 8.2.1

Thx!

**Comment by tmszi** [comment]
GRASS GIS session Python library is a standalone project https://github.com/zarch/grass-session 

Problematic is this code line (missing quotes around `{path}` interpolation key):

https://github.com/zarch/grass-session/blob/d86f78137e259a55d9f7fd86ec2a40a67193002a/grass_session/session.py#L316-L318

```python
    cmd = "{grassbin} -c {create_opts} -e {path}" "".format(
        grassbin=grassbin, create_opts=create_opts, path=path
    )
```

should be 

```python
    cmd = '{grassbin} -c {create_opts} -e "{path}"'.format(
        grassbin=grassbin, create_opts=create_opts, path=path
    )
```
