### ISSUE TITLE
[Bug] TypeError: %b requires a bytes-like object, or an object that implements bytes, not 'str'

### ISSUE THREAD

**Issue by Geek-007** [OSGeo/grass#3155]
Hi everyone, I am getting the error when I execute the following command.
Can anyone tell me how to fix this error, I have tested multiple versions of grass gis and all are like this。

[guest@localhost ]$ `grass72 -c EPSG:3413 ./Gtmp`
          __________  ___   __________    _______________
         / ____/ __ \/   | / ___/ ___/   / ____/  _/ ___/
        / / __/ /_/ / /| | \__ \\_  \   / / __ / / \__ \
       / /_/ / _, _/ ___ |___/ /__/ /  / /_/ // / ___/ /
       \____/_/ |_/_/  |_/____/____/   \____/___//____/

/usr/local/bin/grass72:1431: DeprecationWarning: lgettext() is deprecated, use gettext() instead
  sys.stderr.write(_("Welcome to GRASS GIS %s") % grass_version)
Traceback (most recent call last):
  File "/usr/local/bin/grass72", line 1987, in <module>
    main()
  File "/usr/local/bin/grass72", line 1944, in main
    say_hello()
  File "/usr/local/bin/grass72", line 1431, in say_hello
    sys.stderr.write(_("Welcome to GRASS GIS %s") % grass_version)
**TypeError: %b requires a bytes-like object, or an object that implements __bytes__, not 'str'**

**Comment by nilason** [comment]
The GRASS version you use is apparently 7.2, which dates to 2016-2017, is no longer supported. I suggest you to update to at least 7.8.8, but preferably 8.3.0.
