### ISSUE TITLE
[Bug] Docker build fails for ubuntu_wxgui in CI

### ISSUE THREAD

**Issue by wenzeslaus** [OSGeo/grass#3225]
**Describe the bug**

_Docker / build and push ubuntu_wxgui for refs/heads/main (push)_ fails in CI on main.

See recent commits on main: https://github.com/OSGeo/grass/commits/main

**System description**

https://github.com/OSGeo/grass/tree/main/docker/ubuntu_wxgui
https://github.com/OSGeo/grass/actions/runs/6788175695/workflow

**Additional context**

The other Ubuntu build (without wxPython) works. The build worked 4 days ago. 

**Log**

```
...
#9 123.6       checking if expat.h is valid C++ header... yes
#9 123.6       checking for XML_ParserCreate in -lexpat... yes
#9 123.6       checking for LIBCURL... yes
#9 123.6       checking for GTK+ version...
#9 123.6       checking for pkg-config... (cached) /usr/bin/pkg-config
#9 123.6       checking pkg-config is at least version 0.16... yes
#9 123.6       checking for GTK+ - version >= 3.0.0... Package gtk+-3.0 was not found in the pkg-config search path.
#9 123.6       Perhaps you should add the directory containing `gtk+-3.0.pc'
#9 123.6       to the PKG_CONFIG_PATH environment variable
#9 123.6       No package 'gtk+-3.0' found
#9 123.6       no
#9 123.6       *** Could not run GTK+ test program, checking why...
#9 123.6       *** The test program failed to compile or link. See the file config.log for the
#9 123.6       *** exact error that occurred. This usually means GTK+ is incorrectly installed.
#9 123.6       configure: error:
#9 123.6       The development files for GTK+ were not found. For GTK+ 2, please
#9 123.6       ensure that pkg-config is in the path and that gtk+-2.0.pc is
#9 123.6       installed. For GTK+ 1.2 please check that gtk-config is in the path,
#9 123.6       and that the version is 1.2.3 or above. Also check that the
#9 123.6       libraries returned by 'pkg-config gtk+-2.0 --libs' or 'gtk-config
#9 123.6       --libs' are in the LD_LIBRARY_PATH or equivalent.
#9 123.6       
#9 123.6       Error running configure
#9 123.6       ERROR: failed building wxWidgets
#9 123.6       Traceback (most recent call last):
#9 123.6         File "/tmp/pip-install-0qf_kne1/wxpython_7cedfae100314d928abb887186cd46fd/build.py", line 1563, in cmd_build_wx
#9 123.6           wxbuild.main(wxDir(), build_options)
#9 123.6         File "/tmp/pip-install-0qf_kne1/wxpython_7cedfae100314d928abb887186cd46fd/buildtools/build_wxwidgets.py", line 379, in main
#9 123.6           exitIfError(wxBuilder.configure(dir=wxRootDir, options=configure_opts),
#9 123.6         File "/tmp/pip-install-0qf_kne1/wxpython_7cedfae100314d928abb887186cd46fd/buildtools/build_wxwidgets.py", line 72, in exitIfError
#9 123.6           raise builder.BuildError(msg)
#9 123.6       buildtools.builder.BuildError: Error running configure
#9 123.6       Finished command: build_wx (0m4.651s)
#9 123.6       Finished command: build (0m4.651s)
#9 123.6       Command '"/usr/bin/python3" -u build.py build' failed with exit code 1.
#9 123.6       [end of output]
#9 123.6   
#9 123.6   note: This error originates from a subprocess, and is likely not a problem with pip.
#9 123.6   ERROR: Failed building wheel for wxPython
#9 123.6   Running setup.py clean for wxPython
#9 123.8 Failed to build wxPython
#9 123.9 Installing collected packages: wxPython
#9 123.9   Running setup.py install for wxPython: started
#9 129.0   Running setup.py install for wxPython: finished with status 'error'
#9 129.0   error: subprocess-exited-with-error
#9 129.0   
#9 129.0   × Running setup.py install for wxPython did not run successfully.
#9 129.0   │ exit code: 1
#9 129.0   ╰─> [136 lines of output]
#9 129.0       running install
#9 129.0       /usr/lib/python3/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
#9 129.0         warnings.warn(
#9 129.0       running build
#9 129.0       WARNING: Building this way assumes that all generated files have been
#9 129.0       generated already.  If that is not the case then use build.py directly
#9 129.0       to generate the source and perform the build stage.  You can use
#9 129.0       --skip-build with the bdist_* or install commands to avoid this
#9 129.0       message and the wxWidgets and Phoenix build steps in the future.
#9 129.0       
#9 129.0       "/usr/bin/python3" -u build.py build
#9 129.0       /tmp/pip-install-0qf_kne1/wxpython_7cedfae100314d928abb887186cd46fd/build.py:43: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
#9 129.0         from distutils.dep_util import newer, newer_group
#9 129.0       Will build using: "/usr/bin/python3"
#9 129.0       3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]
#9 129.0       Python's architecture is 64bit
#9 129.0       cfg.VERSION: 4.2.1
#9 129.0       
#9 129.0       Running command: build
#9 129.0       Running command: build_wx
#9 129.0       wxWidgets build options: ['--wxpython', '--unicode', '--gtk3']
#9 129.0       Configure options: ['--enable-unicode', '--with-gtk=3', '--enable-sound', '--enable-graphics_ctx', '--enable-display', '--enable-geometry', '--enable-debug_flag', '--enable-optimise', '--disable-debugreport', '--enable-uiactionsim', '--enable-autoidman', '--with-sdl']
#9 129.0       /tmp/pip-install-0qf_kne1/wxpython_7cedfae100314d928abb887186cd46fd/ext/wxWidgets/configure --enable-unicode --with-gtk=3 --enable-sound --enable-graphics_ctx --enable-display --enable-geometry --enable-debug_flag --enable-optimise --disable-debugreport --enable-uiactionsim --enable-autoidman --with-sdl
#9 129.0       checking build system type... x86_64-pc-linux-gnu
#9 129.0       checking host system type... x86_64-pc-linux-gnu
#9 129.0       checking for toolkit... gtk
#9 129.0       checking for gcc... gcc
...
#9 129.0       checking for GTK+ version...
#9 129.0       checking for pkg-config... (cached) /usr/bin/pkg-config
#9 129.0       checking pkg-config is at least version 0.16... yes
#9 129.0       checking for GTK+ - version >= 3.0.0... Package gtk+-3.0 was not found in the pkg-config search path.
#9 129.0       Perhaps you should add the directory containing `gtk+-3.0.pc'
#9 129.0       to the PKG_CONFIG_PATH environment variable
#9 129.0       No package 'gtk+-3.0' found
#9 129.0       no
#9 129.0       *** Could not run GTK+ test program, checking why...
#9 129.0       *** The test program failed to compile or link. See the file config.log for the
#9 129.0       *** exact error that occurred. This usually means GTK+ is incorrectly installed.
#9 129.0       configure: error:
#9 129.0       The development files for GTK+ were not found. For GTK+ 2, please
#9 129.0       ensure that pkg-config is in the path and that gtk+-2.0.pc is
#9 129.0       installed. For GTK+ 1.2 please check that gtk-config is in the path,
#9 129.0       and that the version is 1.2.3 or above. Also check that the
#9 129.0       libraries returned by 'pkg-config gtk+-2.0 --libs' or 'gtk-config
#9 129.0       --libs' are in the LD_LIBRARY_PATH or equivalent.
#9 129.0       
#9 129.0       Error running configure
#9 129.0       ERROR: failed building wxWidgets
#9 129.0       Traceback (most recent call last):
#9 129.0         File "/tmp/pip-install-0qf_kne1/wxpython_7cedfae100314d928abb887186cd46fd/build.py", line 1563, in cmd_build_wx
#9 129.0           wxbuild.main(wxDir(), build_options)
#9 129.0         File "/tmp/pip-install-0qf_kne1/wxpython_7cedfae100314d928abb887186cd46fd/buildtools/build_wxwidgets.py", line 379, in main
#9 129.0           exitIfError(wxBuilder.configure(dir=wxRootDir, options=configure_opts),
#9 129.0         File "/tmp/pip-install-0qf_kne1/wxpython_7cedfae100314d928abb887186cd46fd/buildtools/build_wxwidgets.py", line 72, in exitIfError
#9 129.0           raise builder.BuildError(msg)
#9 129.0       buildtools.builder.BuildError: Error running configure
#9 129.0       Finished command: build_wx (0m4.769s)
#9 129.0       Finished command: build (0m4.770s)
#9 129.0       Command '"/usr/bin/python3" -u build.py build' failed with exit code 1.
#9 129.0       [end of output]
#9 129.0   
#9 129.0   note: This error originates from a subprocess, and is likely not a problem with pip.
#9 129.0 error: legacy-install-failure
#9 129.0 
#9 129.0 × Encountered error while trying to install package.
#9 129.0 ╰─> wxPython
#9 129.0 
#9 129.0 note: This is an issue with the package mentioned above, not pip.
#9 129.0 hint: See above for output from the failure.
#9 ERROR: process "/bin/bash -c pip install -U     -f https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-22.04     wxPython     && pip cache purge" did not complete successfully: exit code: 1
------
 > [ 4/29] RUN pip install -U     -f https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-22.04     wxPython     && pip cache purge:
129.0       [end of output]
129.0   
129.0   note: This error originates from a subprocess, and is likely not a problem with pip.
129.0 error: legacy-install-failure
129.0 
129.0 × Encountered error while trying to install package.
129.0 ╰─> wxPython
129.0 
129.0 note: This is an issue with the package mentioned above, not pip.
129.0 hint: See above for output from the failure.
------
Dockerfile:105
--------------------
 104 |     # wxGUI
 105 | >>> RUN pip install -U \
 106 | >>>     -f https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-22.04 \
 107 | >>>     wxPython \
 108 | >>>     && pip cache purge
 109 |     # If you do not use any Gnome Accessibility features, to suppress warning
--------------------
ERROR: failed to solve: process "/bin/bash -c pip install -U     -f https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-22.04     wxPython     && pip cache purge" did not complete successfully: exit code: 1
Error: buildx failed with: ERROR: failed to solve: process "/bin/bash -c pip install -U     -f https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-22.04     wxPython     && pip cache purge" did not complete successfully: exit code: 1
```

**Comment by wenzeslaus** [comment]
Maybe a separate check which would build all the Docker images is needed for PRs so that we see the issue before it hits main?

**Comment by wenzeslaus** [comment]
_Docker / build and push ubuntu_wxgui for refs/heads/main (push)_ fails for two commits on main, but it now finished successfully for two new commits. I'm closing this.
