### ISSUE TITLE
[Bug] g.gui.animation animation speed change fails

### ISSUE THREAD

**Issue by landam** [OSGeo/grass#3580]
**Describe the bug**
Change animation speed fails:

```py
Traceback (most recent call last):
  File "/home/martin/src/grass/dist.x86_64-pc-linux-gnu/gui/wxpython/animation/toolbars.py", line 177, in OnPlayForward
    self.parent.OnPlayForward(event)
  File "/home/martin/src/grass/dist.x86_64-pc-linux-gnu/gui/wxpython/animation/frame.py", line 263, in OnPlayForward
    self.controller.StartAnimation()
  File "/home/martin/src/grass/dist.x86_64-pc-linux-gnu/gui/wxpython/animation/controller.py", line 113, in StartAnimation
    self.timer.Start(self.timeTick)
TypeError: Timer.Start(): argument 1 has unexpected type 'float'
```

**To Reproduce**

1. Create strds by `r.lake.series`
2. Open `g.gui.animation strds=sample`
3. Load space-time raster dataset
4. Change animation speed
5. Play

**Expected behavior**
Animation speed may be changed.

**System description (please complete the following information):**

- Operating System: Linux
- GRASS GIS version 8.4

**Comment by tmszi** [comment]
I confirm this issue, and nviz record animation has same issue too.

```
Traceback (most recent call last):
  File "/usr/lib64/grass84/gui/wxpython/nviz/tools.py", line
2604, in OnRecord

anim.Start()
  File "/usr/lib64/grass84/gui/wxpython/nviz/animation.py",
line 62, in Start

self.timer.Start(self.GetInterval())
TypeError
:
Timer.Start(): argument 1 has unexpected type 'float'
```
