### ISSUE TITLE
[Bug] r.texture: test_sv fails on Mac with arm64

### ISSUE THREAD

**Issue by cyliang368** [OSGeo/grass#3796]
## Describe the bug

One test on the `r.texture` module failed when running the sv method on MacOS in PR #3786. The values are different from those from WSL. Actually, the other methods derive slightly different values of no more than 1e-2. This error can be reproduced on my own Macbook with an M1 chip. 

See the detailed testing result below:

<details>

```
========================================================================
...........F.
======================================================================
FAIL: test_sv (__main__.TestRasterreport.test_sv)
Testing method sv
----------------------------------------------------------------------
Traceback (most recent call last):
  File "raster/r.texture/testsuite/test_texture.py", line 133, in test_sv
    self.assertRasterFitsUnivar(output, reference=values, precision=1e-2)
  File "etc/python/grass/gunittest/case.py", line 289, in assertRasterFitsUnivar
    self.assertModuleKeyValue(
  File "etc/python/grass/gunittest/case.py", line 271, in assertModuleKeyValue
    self.fail(self._formatMessage(msg, stdMsg))
AssertionError: r.univar map=sv_SV percentile=90.0 nprocs=1 separator== -g difference:
mismatch values (key, reference, actual): [('max', 45368492, 45368496), ('mean', 2248724.35829364, 2248724.38215788), ('variance', 2332049431762.5, 2332049495199.41)]
command: r.univar map=sv_SV percentile=90.0 nprocs=1 separator== -g {'map': 'sv_SV', 'separator': '=', 'flags': 'g'}

----------------------------------------------------------------------
Ran 13 tests in 17.564s
FAILED (failures=1)
========================================================================
FAILED ./raster/r.texture/testsuite/test_texture.py (1 test failed)
```

</details>

## To reproduce

1. Fetch the `test_texture.py` file in PR #3786. 
2. Use `precision=1e-2` for every unit test function.
3. Run this test file on an arm-based macOS machine.

## Expected behavior

Only test_sv fails, and others pass. It should show:
```
mismatch values (key, reference, actual): [('max', 45368492, 45368496), ('mean', 2248724.35829364, 2248724.38215788), ('variance', 2332049431762.5, 2332049495199.41)]
```
 If you use a smaller precision, you may see more tests fail.

## System description

OS: macOS (arm chip)
GRASS GIS version: 8.4.0

## Additional context

#3395, #3397, and #3398 reported similar/same bug. Not sure if this bug happens in `r.texture` or `r.univar`.

**Comment by echoix** [comment]
About the question in a review comment if it occurs only on Apple silicon arm or any arm, does anyone have a raspberry pi available to try this on?

**Comment by nilason** [comment]
> About the question in a review comment if it occurs only on Apple silicon arm or any arm, does anyone have a raspberry pi available to try this on?

Travis could perhaps be an alternative: https://docs.travis-ci.com/user/multi-cpu-architectures.

**Comment by cyliang368** [comment]
I tried adding a `-fno-fast-math` cflag and compiled `r.texture`. The Arm64 Mac gives the same results as those from x86. I believe we should put this flag in a Makefile or configure. Unfortunately, I am not familiar with this. Could someone help me?

Please see this post: https://stackoverflow.com/questions/64036879/differing-floating-point-calculation-results-between-x86-64-and-armv8-2-a

**Comment by echoix** [comment]
I'll reply tonight!

**Comment by echoix** [comment]
Ok, it's nice to see that the issue is solvable that easily, and you tried it!
I'm wondering if it's still possible for us to do something better so the compiler doesn't get to do that kind of change, but in the meantime, a flag might be worth it.

I don't know what @nilason would think of it, but as mentioned in the SO thread linked, the flag could be added only for arm builds. In CI, that would mean only macOS.

My questions:
- Does configure (autotools) allow arch-specific flags?
- Can the flag be (safely) added only to a single object file, not the whole library+modules?

**Comment by cyliang368** [comment]
The ARM's official website provides explanations of what they do for this flag and compilation: https://developer.arm.com/documentation/101754/0622/armclang-Reference/armclang-Command-line-Options/-ffast-math---fno-fast-math

I can create a PR that applies this change to `r.texture` first, and then we can consider whether we need to use it for the whole library later. In my opinion, this flag should be applied to the library to ensure the IEEE754 is followed because we are doing scientific computing. We should involve more people in this discussion regarding the change for the entire library.

**Comment by nilason** [comment]
> I tried adding a `-fno-fast-math` cflag and compiled `r.texture`. The Arm64 Mac gives the same results as those from x86. I believe we should put this flag in a Makefile or configure. Unfortunately, I am not familiar with this. Could someone help me?

Great findings! Setting `-ffp-contract=fast` also makes r.texture and r3.flow pass the tests. Let us not rush this, let's try understand first. (https://clang.llvm.org/docs/UsersManual.html#controlling-floating-point-behavior)

**Comment by nilason** [comment]
Now, this is an issue again on the CI runner.

**Comment by nilason** [comment]
CI just bumped the clang version from 19.1.7 to 20.1.1.

test_rtexture.py/test_rtexture_parallel.py:

```
mismatch values (key, reference, actual): [('max', 45368496, 45368492), ('mean', 2248724.38215788, 2248724.35922656), ('variance', 2332049495199.41, 2332049429651.92)]
```

**Comment by nilason** [comment]
I seems to me `-ffp-contract=fast ` is the default on GCC causing this discrepancy.

https://kristerw.github.io/2021/11/09/fp-contract/
https://gcc.gnu.org/pipermail/gcc/2023-September/242510.html

We should probably add this flag to the Mac CI runner, for consistency.

**Comment by wenzeslaus** [comment]
Don't we need `-ffp-contract=off` and/or `-fno-fast-math` and use those test numbers instead of trying to match a non-guaranteed result across platforms and compilers?

**Comment by nilason** [comment]
> Don't we need `-ffp-contract=off` and/or `-fno-fast-math` and use those test numbers instead of trying to match a non-guaranteed result across platforms and compilers?

I'll try that first in a separate branch on my fork. The reason I hesitated to that, was that this will affect any developer (compiling with default GCC) too, running the tests locally. I wouldn't want to inject this to configure.

**Comment by nilason** [comment]
Now I see [GCC docs](https://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html#index-ffp-contract) too mention this:

> The default is -ffp-contract=off for C in a standards compliant mode (-std=c11 or similar), -ffp-contract=fast otherwise.

Our code is not pure C11, if I remember correctly, it needs gnu11.

**Comment by nilason** [comment]
> Now I see [GCC docs](https://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html#index-ffp-contract) too mention this:
> 
> > The default is -ffp-contract=off for C in a standards compliant mode (-std=c11 or similar), -ffp-contract=fast otherwise.
> 
> Our code is not pure C11, if I remember correctly, it needs gnu11.

I use `-std=c11` locally though, so maybe that is now a possibility... If this would work, I wouldn't mind add -std=c11 to configure.

**Comment by nilason** [comment]
Some good background: https://stackoverflow.com/a/74077323
