### ISSUE TITLE
[Bug] g.gui.gmodeler: adding solely data fails

### ISSUE THREAD

**Issue by pesekon2** [OSGeo/grass#3863]
## Describe the bug

If I try to add data using the `Add data` item from the menu, nothing happens, raising the following error:

```python
Traceback (most recent call last):
  File "/home/pesek/workspace/grass/dist.x86_64-pc-linux-gnu/gui/wxpython/gmodeler/panels.py", line 1139, in OnAddData
    data = ModelData(
  File "/home/pesek/workspace/grass/dist.x86_64-pc-linux-gnu/gui/wxpython/gmodeler/model.py", line 1395, in __init__
    self._setPen()
  File "/home/pesek/workspace/grass/dist.x86_64-pc-linux-gnu/gui/wxpython/gmodeler/model.py", line 1552, in _setPen
    self.SetPen(self._getPen())
```

## Expected behavior

Pop up a dialog.

## System description

* Operating System: Linux (Ubuntu)
* GRASS GIS version: main as of https://github.com/OSGeo/grass/commit/ae7163c50e1d8f46b9c5871e3de96b973cf20f0f

**Comment by pesekon2** [comment]
Introduced in #3400. The menu item is just containing a parent class instead of a child one (therefore, the methods that should be inherited from the 2nd parent are missing).
