### ISSUE TITLE
[Bug] t.info: 'RasterMetadata' object has no attribute 'print_info'

### ISSUE THREAD

**Issue by veroandreo** [OSGeo/grass#4076]
## Describe the bug
According to the manual page [t.info](https://grass.osgeo.org/grass83/manuals/t.info.html) not only prints metadata about time series, but also about single maps registered in the temporal database. However, when attempting to print metadata for a single raster file already registered, I get:

```
t.info lst_2014.005_avg type=raster
 +-------------------- Raster Dataset ----------------------------------------+
 |                                                                            |
 +-------------------- Basic information -------------------------------------+
 | Id: ........................ lst_2014.005_avg@italy_LST_daily
 | Name: ...................... lst_2014.005_avg
 | Mapset: .................... italy_LST_daily
 | Creator: ................... veroandreo
 | Temporal type: ............. absolute
 | Creation time: ............. 2021-08-10 18:06:49
 +-------------------- Absolute time -----------------------------------------+
 | Start time:................. 2014-01-05 00:00:00
 | End time:................... 2014-01-06 00:00:00
 +-------------------- Spatial extent ----------------------------------------+
 | North:...................... 2666000.0
 | South:...................... 2228000.0
 | East:.. .................... 4635000.0
 | West:....................... 4053000.0
 | Top:........................ 0.0
 | Bottom:..................... 0.0
Traceback (most recent call last):
  File "/home/vandreo/software/grass-dev/dist.x86_64-pc-linux-gnu/scripts/t.info", line 134, in <module>
    main()
  File "/home/vandreo/software/grass-dev/dist.x86_64-pc-linux-gnu/scripts/t.info", line 129, in main
    dataset.print_info()
  File "/home/vandreo/software/grass-dev/dist.x86_64-pc-linux-gnu/etc/python/grass/temporal/abstract_map_dataset.py", line 308, in print_info
    self.metadata.print_info()
    ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'RasterMetadata' object has no attribute 'print_info'
```

## To reproduce

```
for i in $(seq 1 5) ; do 
r.mapcalc expression="map_${i} = ${i}" 
done

t.create type=strds temporaltype=absolute output=test title="test" description="test"

t.register input=test maps=`g.list rast pat=map* sep=comma` start="2024-07-14" increment="1 days" -i

t.info map_1 type=raster
```

## System description
```
version=8.5.0dev
date=2024
revision=ee9fa48798
build_date=2024-07-11
build_platform=x86_64-pc-linux-gnu
build_off_t_size=8
proj=9.2.1
gdal=3.7.1
geos=3.12.0
sqlite=3.42.0
```

**Comment by veroandreo** [comment]
Closing in favor of #4182.
