### ISSUE TITLE
[Bug] wxPython error when launching GRASS GUI on Ubuntu 22.04

### ISSUE THREAD

**Issue by fsdias** [OSGeo/grass#4491]
When I try to run GRASS from the desktop the GUI doesn’t open. Running the GUI from the command prompt returns an error related to wxpython.

```
GRASS tmpproject/PERMANENT:~ > g.gui.wxpython
g.gui.wxpython: comando não encontrado
GRASS tmpproject/PERMANENT:~ > g.gui wxpython
Launching <wxpython> GUI in the background, please wait...
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/wx/core.py", line 3427, in <lambda>
    lambda event: event.callable(*event.args, **event.kw) )
  File "/usr/lib/grass84/gui/wxpython/wxgui.py", line 93, in show_main_gui
    mainframe = GMFrame(
  File "/usr/lib/grass84/gui/wxpython/main_window/frame.py", line 181, in __init__
    self.workspace_manager.CreateRecentFilesMenu(
  File "/usr/lib/grass84/gui/wxpython/lmgr/workspace.py", line 517, in CreateRecentFilesMenu
    file_menu = menu.GetMenu(
wx._core.wxAssertionError: C++ assertion ""node"" failed at ./src/common/menucmn.cpp(923) in GetMenu(): bad index in wxMenuBar::GetMenu()
```

Failed troubleshooting steps:

- Deleted ~/.grass8/

-  ugrade wxpython from 4.2 to 4.2.2 with` pip3 install -U -f https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-22.04 wxPython`

**System information:**
Operating System: Pop OS 22.04 (Ubuntu 22.04)
GRASS GIS 8.4.0
UbuntuGIS unstable

```
version=8.4.0
date=2024
revision=exported
build_date=2024-07-29
build_platform=x86_64-pc-linux-gnu
build_off_t_size=8
libgis_revision=8.4.0
libgis_date=2024-07-29T15:34:12+00:00
proj=9.3.1
gdal=3.8.4
geos=3.12.1
sqlite=3.37.2
```
```
python3 -c "import sys, wx; print(sys.version); print(wx.version())"
3.10.12 (main, Sep 11 2024, 15:47:36) [GCC 11.4.0]
4.2.1 gtk3 (phoenix) wxWidgets 3.2.4
```

**Comment by petrasovaa** [comment]
This is a duplicate of #3222. What is your locale?

**Comment by fsdias** [comment]
> This is a duplicate of #3222. What is your locale?

$ locale
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE=pt_PT.UTF-8
LC_NUMERIC=pt_PT.UTF-8
LC_TIME=pt_PT.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=pt_PT.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=pt_PT.UTF-8
LC_NAME=pt_PT.UTF-8
LC_ADDRESS=pt_PT.UTF-8
LC_TELEPHONE=pt_PT.UTF-8
LC_MEASUREMENT=pt_PT.UTF-8
LC_IDENTIFICATION=pt_PT.UTF-8
LC_ALL=
