### ISSUE TITLE
[Bug] r.buildvrt generated map used as MASK crashes r.out.gdal

### ISSUE THREAD

**Issue by neteler** [OSGeo/grass#459]
**Describe the bug**

Using a map generated with `r.buildvrt` as raster MASK, and then exporting a map with `r.out.gdal` crashes `r.out.gdal`.

**To Reproduce**

Example from `r.buildvrt` (https://grass.osgeo.org/grass78/manuals/r.buildvrt.html#examples), VRT from a DEM tileset in the North Carolina sample dataset, which is then used as MASK:

```
# set the region
g.region raster=elev_state_500m -p
# higher resolution
g.region res=50 -p
# resample the DEM to 50 meter
r.resamp.interp input=elev_state_500m output=elev_state_50m method=bilinear
# create tiles
r.tile input=elev_state_50m output=elev_state_50m_tile_ width=1000 height=1000 overlap=0
# dump list of tiles to a file
g.list type=raster pattern=elev_state_50m_tile_* output=tilelist
# build a vrt
r.buildvrt file=tilelist output=elev_state_50m_vrt

# use VRT as a MASK
r.mask raster=elev_state_50m_vrt  
All subsequent raster operations will be limited to the MASK area. Removing
or renaming raster map named 'MASK' will restore raster operations to
normal.
[Raster MASK present]

r.out.gdal input=elevation output=bla.tif create="COMPRESS=LZW"
Checking GDAL data type and nodata value...
Segmentation fault (core dumped)
[Raster MASK present]
```

The segmentation fault problem is likely a conceptual one ("GDAL on top of GDAL").

**Debugging**

```
gdb r.out.gdal
r input=elevation output=bla.tif create="COMPRESS=LZW"

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7f6fe16 in Rast_get_vrt_row (fd=1, buf=0x58c510, row=0, data_type=0) at vrt.c:208
208		    for (j = 0; j < p->clist->n_values; j++) {
(gdb) bt
#0  0x00007ffff7f6fe16 in Rast_get_vrt_row (fd=1, buf=0x58c510, row=0, data_type=0) at vrt.c:208
#1  0x00007ffff7f5fdd4 in get_map_row_nomask (fd=1, rast=0x58c510, row=0, data_type=0) at get_row.c:567
#2  0x00007ffff7f60a76 in embed_mask (flags=0x588370 '\001' <repeats 200 times>..., row=0) at get_row.c:994
#3  0x00007ffff7f60c06 in get_null_value_row (fd=0, flags=0x588370 '\001' <repeats 200 times>..., row=0, with_mask=1) at get_row.c:1023
#4  0x00007ffff7f60cc5 in embed_nulls (fd=0, buf=0x577d30, row=0, map_type=1, null_is_zero=0, with_mask=1) at get_row.c:1042
#5  0x00007ffff7f5ff04 in get_map_row_no_reclass (fd=0, rast=0x577d30, row=0, data_type=1, null_is_zero=0, with_mask=1) at get_row.c:593
#6  0x00007ffff7f5ffde in get_map_row (fd=0, rast=0x577d30, row=0, data_type=1, null_is_zero=0, with_mask=1) at get_row.c:616
#7  0x00007ffff7f6016b in Rast_get_row (fd=0, buf=0x577d30, row=0, data_type=1) at get_row.c:761
#8  0x000000000040422a in exact_checks (export_datatype=GDT_Float32, name=0x4de050 "elevation", mapset=0x4de150 "PERMANENT", cellhead=0x7fffffffceb0, maptype=1, 
    nodataval=-nan(0x8000000000000), nodatakey=0x409c25 "nodata", default_nodataval=1) at export_band.c:77
#9  0x00000000004071e9 in main (argc=5, argv=0x7fffffffd0c8) at main.c:535
```

This happens both in G7.8 as well as master.

**Comment by metzm** [comment]
Fixed in master 4848bfc and relbr78 7802cad.
