### ISSUE TITLE
[Bug] Unable use the Temporal Plot Tool on Ubuntu 18.04

### ISSUE THREAD

**Issue by neteler** [OSGeo/grass#489]
**Describe the bug**

(cited from https://gis.stackexchange.com/questions/355146/unable-use-a-temporal-plot-tool-in-grass-gis; with permission)

I installed GRASS GIS following the tutorial on the website for the Ubuntu 18.04 version. However, the Temporal Plot Tool function is not working, and is giving an error related to python.

Below is the error that is giving in the tool.

```
Unable to start Temporal Plot Tool

Motivo: The Temporal Plot Tool needs the "Matplotlib" (python-matploltib) package to be installed. Cannot load backend 'WXAgg' which requires the 'wx' interactive framework, as 'gtk3' is currently running

Traceback (most recent call last)
File "/usr/local/grass78/gui/wxpython/tplot/frame.py", line 36, in <module>
matplolib.use('WXAgg')
File "/home/luiz/.local/lib/python3.6/site-packages/matplotlib/cbook/deprecation.py", line 296, in wrapper
return func(*args, **kwargs)
File "/home/luiz/.local/lib/python3.6/site-packages/matplotlib/cbook/deprecation.py", line 358, in wrapper
return func(*args, **kwargs)
File "/home/luiz/.local/lib/python3.6/site-packages/matplotlib/_init_.py", line 1281 in use 
plt.switch_backend(name)
File "/home/luiz/.local/lib/python3.6/site-packages/matplotlib/pyplot.py", line 237, in switch_backend
newbackend, required_framework, current_framework))
ImportError:Cannot load backend 'WXAgg' which requires the 'wx' interactive framework, as 'gtk3' is currently running

During handling odf the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/local/grass78/gui/wxpython/lmgr/frame.py", line 1930, in OnTplotTool
from tplot.frame import TplotFrame
File "/usr/local/grass78/gui/wxpython/tplot/frame.py", line 45, in 
<module>
'(python-matplotlib) package to be installed. {0}').format(e))
ImportError: The Temporal Plot Tool needs the "matplotlib" (python-matplotlib) package to be installed Cannot load backend 'WXAgg' which requires the 'wx' interactive framework, as 'gtk3' is currently running
```

What should I do to solve this problem?

**System description (please complete the following information):**

- Operating System: Ubuntu 18.04
- GRASS GIS version: 7.8

**Comment by petrasovaa** [comment]
I suppose `sudo apt install python3-matplotlib` should fix that.

**Comment by neteler** [comment]
In lack of no response by the original requester I close this.
Thanks for your comment, Anna.
