### ISSUE TITLE
[Bug] Compilation: ModuleNotFoundError: No module named 'wx'

### ISSUE THREAD

**Issue by neteler** [OSGeo/grass#588]
**Describe the bug**

When compiling on Linux (maybe on other platforms, too), this - ignored - compilation error occurs. It exists for a long time, but should be fixed:

```
...
make[4]: Leaving directory `/builddir/build/BUILD/grass-7.8.3/gui/wxpython'
make menustrings.py
make[4]: Entering directory `/builddir/build/BUILD/grass-7.8.3/gui/wxpython'
/usr/bin/install -c  -m 644 xml/menudata.xml /builddir/build/BUILD/grass-7.8.3/dist.x86_64-redhat-linux-gnu/gui/wxpython/xml/menudata.xml
/usr/bin/install -c  -m 644 xml/module_tree_menudata.xml /builddir/build/BUILD/grass-7.8.3/dist.x86_64-redhat-linux-gnu/gui/wxpython/xml/module_tree_menudata.xml
GISRC=/builddir/build/BUILD/grass-7.8.3/dist.x86_64-redhat-linux-gnu/demolocation/.grassrc78 GISBASE=/builddir/build/BUILD/grass-7.8.3/dist.x86_64-redhat-linux-gnu PATH="/builddir/build/BUILD/grass-7.8.3/dist.x86_64-redhat-linux-gnu/bin:/builddir/build/BUILD/grass-7.8.3/dist.x86_64-redhat-linux-gnu/bin:/builddir/build/BUILD/grass-7.8.3/dist.x86_64-redhat-linux-gnu/scripts:$PATH" PYTHONPATH="/builddir/build/BUILD/grass-7.8.3/dist.x86_64-redhat-linux-gnu/etc/python:/builddir/build/BUILD/grass-7.8.3/dist.x86_64-redhat-linux-gnu/gui/wxpython:$PYTHONPATH" LD_LIBRARY_PATH="/builddir/build/BUILD/grass-7.8.3/dist.x86_64-redhat-linux-gnu/bin:/builddir/build/BUILD/grass-7.8.3/dist.x86_64-redhat-linux-gnu/bin:/builddir/build/BUILD/grass-7.8.3/dist.x86_64-redhat-linux-gnu/scripts:/builddir/build/BUILD/grass-7.8.3/dist.x86_64-redhat-linux-gnu/lib:/builddir/build/BUILD/grass-7.8.3/dist.x86_64-redhat-linux-gnu/lib:" LC_ALL=C LANG=C LANGUAGE=C python3 core/menutree.py "manager" >> menustrings.py
Traceback (most recent call last):
  File "core/menutree.py", line 46, in <module>
    import wx
ModuleNotFoundError: No module named 'wx'
make[4]: *** [menustrings.py] Error 1
make[4]: Leaving directory `/builddir/build/BUILD/grass-7.8.3/gui/wxpython'
make parsubdirs
make[3]: [default] Error 2 (ignored)
make[4]: Entering directory `/builddir/build/BUILD/grass-7.8.3/gui/wxpython'
...
```

**Expected behavior**
This error shouldn't appear.

**System description (please complete the following information):**

- Operating System: EPEL7 (but also other Linux distros)
- GRASS GIS version: 7.8.3 and master

**Comment by petrasovaa** [comment]
I would check the Python environment. menutree.py is called from the wxgui Makefile:
```
menustrings.py: core/menutree.py $(DSTDIR)/xml/menudata.xml $(DSTDIR)/xml/module_tree_menudata.xml $(DSTDIR)/xml/menudata_modeler.xml $(DSTDIR)/xml/menudata_psmap.xml
	@echo "# This is a generated file.\n" > $@
	$(call run_grass,$(PYTHON) $< "manager" >> $@)
	$(call run_grass,$(PYTHON) $< "module_tree" >> $@)
	$(call run_grass,$(PYTHON) $< "modeler" >> $@)
	$(call run_grass,$(PYTHON) $< "psmap" >> $@)
```
Is it possible $(PYTHON) is not python3 but python 2 where you don't have wx?

**Comment by neteler** [comment]
I cannot reproduce it any more on Fedora but on EPEL it still occurs.
Maybe a low prio issue.

No idea about Mac and Windows here, if it occurs also there.

**Comment by petrasovaa** [comment]
Are you sure wx is installed there? We should still fix that even for cases when wx is not available.

**Comment by neteler** [comment]
While I tried to include wx in https://download.copr.fedorainfracloud.org/results/neteler/grass78/epel-7-x86_64/01369114-grass/grass.spec

it seems to be missing (so, the `if` condition in the SPEC file is apparently wrong):

https://download.copr.fedorainfracloud.org/results/neteler/grass78/epel-7-x86_64/01369114-grass/builder-live.log.gz

BTW, which wx package to use?
- https://centos.pkgs.org/7/epel-x86_64/wxPython-2.8.12.0-9.el7.x86_64.rpm.html
- https://centos.pkgs.org/7/epel-x86_64/python36-wxpython4-4.0.7-4.el7.x86_64.rpm.html

Then I try to fix the SPEC file accordingly.

**Comment by petrasovaa** [comment]
Use the second one 4.0.7, the first one is very old.

**Comment by nilason** [comment]
I cannot replicate this on my dev setup on mac. But I found it in a macports log:

```
:info:build GISRC=/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_release_tarballs_ports_gis_grass7/grass7/work/grass-7.8.3/dist.x86_64-apple-darwin18.7.0/demolocation/.grassrc78 GISBASE=/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_release_tarballs_ports_gis_grass7/grass7/work/grass-7.8.3/dist.x86_64-apple-darwin18.7.0 PATH="/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_release_tarballs_ports_gis_grass7/grass7/work/grass-7.8.3/dist.x86_64-apple-darwin18.7.0/bin:/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_release_tarballs_ports_gis_grass7/grass7/work/grass-7.8.3/dist.x86_64-apple-darwin18.7.0/bin:/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_release_tarballs_ports_gis_grass7/grass7/work/grass-7.8.3/dist.x86_64-apple-darwin18.7.0/scripts:$PATH" PYTHONPATH="/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_release_tarballs_ports_gis_grass7/grass7/work/grass-7.8.3/dist.x86_64-apple-darwin18.7.0/etc/python:/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_release_tarballs_ports_gis_grass7/grass7/work/grass-7.8.3/dist.x86_64-apple-darwin18.7.0/gui/wxpython:$PYTHONPATH" DYLD_LIBRARY_PATH="/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_release_tarballs_ports_gis_grass7/grass7/work/grass-7.8.3/dist.x86_64-apple-darwin18.7.0/bin:/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_release_tarballs_ports_gis_grass7/grass7/work/grass-7.8.3/dist.x86_64-apple-darwin18.7.0/bin:/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_release_tarballs_ports_gis_grass7/grass7/work/grass-7.8.3/dist.x86_64-apple-darwin18.7.0/scripts:/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_release_tarballs_ports_gis_grass7/grass7/work/grass-7.8.3/dist.x86_64-apple-darwin18.7.0/lib:/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_release_tarballs_ports_gis_grass7/grass7/work/grass-7.8.3/dist.x86_64-apple-darwin18.7.0/lib:" LC_ALL=C LANG=C LANGUAGE=C /opt/local/bin/python3.7 core/menutree.py "manager" >> menustrings.py
:info:build Traceback (most recent call last):
:info:build   File "core/menutree.py", line 46, in <module>
:info:build     import wx
:info:build ModuleNotFoundError: No module named 'wx'
:info:build make[4]: *** [menustrings.py] Error 1
:info:build make[4]: Leaving directory `/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_release_tarballs_ports_gis_grass7/grass7/work/grass-7.8.3/gui/wxpython'
:info:build make[3]: [default] Error 2 (ignored)
```

**Comment by neteler** [comment]
> Use the second one 4.0.7, the first one is very old.

Will do, once this ticket is addressed:
https://bugzilla.redhat.com/show_bug.cgi?id=1765573

**Comment by neteler** [comment]
With python3-wxpython4 the compilation works fine. Closing.
