### ISSUE TITLE
[Bug] r.in.wms: entire Capabilities file (thousands of bytes) becomes the filename

### ISSUE THREAD

**Issue by jidanni** [OSGeo/grass#622]
Did this ever work?
Why does the entire Capabilities file (thousands of bytes) become the filename
```
Executing <r.in.wms --verbose driver=WMTS_GRASS url=https://wmts.nlsc.gov.tw/wmts layers=LAND_OPENDATA output=LAND_OPENDATA> ...
NS and EW resolutions are different
NS and EW resolutions are different
NS and EW resolutions are different
NS and EW resolutions are different
Downloading data from WMS server...
Traceback (most recent call last):
  File "/usr/lib/grass78/etc/r.in.wms/wms_cap_parsers.py", line 34, in __init__
    etree.ElementTree.__init__(self, file=cap_file)
  File "/usr/lib/python3.8/xml/etree/ElementTree.py", line 555, in __init__
    self.parse(file)
  File "/usr/lib/python3.8/xml/etree/ElementTree.py", line 584, in parse
    source = open(source, "rb")
OSError: [Errno 36] File name too long: '<?xml version="1.0" encoding="UTF-8" standalone="no"?>\r\n<Capabilities xml*....
```

**Comment by jidanni** [comment]
Trying it with the example from the man page......

```
grass /home/jidanni/grassdata/ruanbikeng/TC46 --exec r.in.wms url="http://geoportal.cuzk.cz/WMTS_ORTOFOTO/WMTService.aspx" layers=orto output=orthophoto \
                srs=3857 format=jpeg driver=WMTS_GRASS style=default
Starting GRASS GIS...
Cleaning up temporary files...
Executing <r.in.wms url=http://geoportal.cuzk.cz/WMTS_ORTOFOTO/WMTService.aspx layers=orto output=orthophoto srs=3857 format=jpeg driver=WMTS_GRASS style=default> ...
WARNING: Updating spatial reference with embedded proj4 definition
Downloading data from WMS server...
Traceback (most recent call last):
  File "/usr/lib/grass78/etc/r.in.wms/wms_cap_parsers.py", line 34, in __init__
    etree.ElementTree.__init__(self, file=cap_file)
  File "/usr/lib/python3.8/xml/etree/ElementTree.py", line 555, in __init__
    self.parse(file)
  File "/usr/lib/python3.8/xml/etree/ElementTree.py", line 584, in parse
    source = open(source, "rb")
OSError: [Errno 36] File name too long: '<?xml version="1.0" encoding="utf-8"?>\n<Capabilities xsi:schemaLocation="http://www.opengis.net/wmts/1.0 http://geoportal-orto.cuzk.cz/WMTS_ORTOFOTO/Schemas/wmts.xsd" version="1.0.0" xmlns="http://www.opengis.net/wmts/1.0" xmlns:ows="http://www.opengis.net/ows/1.1" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance
```
