### ISSUE TITLE
[Bug] i.pansharpen: TypeError: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by neteler** [OSGeo/grass#737]
**Describe the bug**
I was about to re-do the screenshots in the i.pansharpen manual, but the module surprisingly crashes:

```
# download Landsat-8 scene from https://earthexplorer.usgs.gov/

# import:
for i in $(seq 1 11) QA ; do
  r.import LC08_L1TP_033032_20180706_20180717_01_T1_B$i.TIF \
       output=$(basename LC08_L1TP_033032_20180706_20180717_01_T1_B$i .TIF)
done

# set current region
g.region raster=LC08_L1TP_033032_20180706_20180717_01_T1_B2 -p

# rescale bands
i.landsat.toar input=LC08_L1TP_033032_20180706_20180717_01_T1_B \
    output=lsat8_boulder. metfile=LC08_L1TP_033032_20180706_20180717_01_T1_MTL.txt 

# set current region to panchromatic channel
g.region raster=lsat8_boulder8 -p

# run PCA pansharpening
i.pansharpen blue=lsat8_boulder2 green=lsat8_boulder3 red=lsat8_boulder4 \
   pan=lsat8_boulder8 output=lsat8_boulder_15m_pca method=pca
Using 8bit image channels
Performing pan sharpening with hi res pan image: 15.000000
Creating PCA images and calculating eigenvectors...
Histogram matching...
 100%
 100%
Histogram matching...
 100%
 100%
Histogram matching...
 100%
 100%
Performing inverse PCA ...
Traceback (most recent call last):
  File "/home/mneteler/software/grass78_git/dist.x86_64-pc-linux-gnu/scripts/i.pansharpen", line 632, in <module>
    main()
  File "/home/mneteler/software/grass78_git/dist.x86_64-pc-linux-gnu/scripts/i.pansharpen", line 261, in main
    pca(pan, ms1, ms2, ms3, out, pid, sproc)
  File "/home/mneteler/software/grass78_git/dist.x86_64-pc-linux-gnu/scripts/i.pansharpen", line 493, in pca
    pb = grass.mapcalc_start('%s_blue = 1 * round((%s * %f) + (%s * %f) + (%s * %f) + %f)'
  File "/home/mneteler/software/grass78_git/dist.x86_64-pc-linux-gnu/etc/python/grass/script/raster.py", line 161, in mapcalc_start
    p.stdin.write(e)
TypeError: a bytes-like object is required, not 'str'
syntax error, unexpected $end, expecting VARNAME or NAME or STRING
Parse error
ERROR: parse error
```

**Expected behavior**
Must not crash :-)

**System description (please complete the following information):**

```
Linux, Fedora 32

Python 3.8.3

g.version -rge
version=7.8.4dev
date=2020
revision=0798df3d0
build_date=2020-06-15
build_platform=x86_64-pc-linux-gnu
build_off_t_size=8
libgis_revision=8e4dab571
libgis_date=2020-05-05T09:05:27+00:00
proj=6.3.2
gdal=3.0.4
geos=3.8.1
sqlite=3.32.1
```

**Comment by cmbarton** [comment]
Is this an issue of switching to Python 3?

**Comment by neteler** [comment]
The first "offending" line:

https://github.com/OSGeo/grass/blob/cade4ace98b43d876ba398f16245db2df60606df/scripts/i.pansharpen/i.pansharpen.py#L493

**Comment by neteler** [comment]
Here another example based on the North Carolina sample dataset:

```
GRASS 7.8.4dev (nc_spm_08_grass7):~ >

g.region raster=lsat7_2000_80 -p
i.pansharpen blue=lsat7_2000_10 green=lsat7_2000_20 red=lsat7_2000_30 pan=lsat7_2000_80 \
  output=lsat7_15m_pca method=pca
i.colors.enhance blue=lsat7_15m_pca_blue green=lsat7_15m_pca_green red=lsat7_15m_pca_red

d.mon wx0
d.rgb blue=lsat7_15m_pca_blue green=lsat7_15m_pca_green red=lsat7_15m_pca_red
```

The pansharpened map is generated, great.

**Comment by neteler** [comment]
Unfortunately there is still one more bug, when using the `-l` flag:

```
i.pansharpen red=lsat7_2002_30   green=lsat7_2002_20 blue=lsat7_2002_10   pan=lsat7_2002_80 method=ihs   output=lsat7_2002_ihs -l
Using 8bit image channels
Performing pan sharpening with hi res pan image: 14.250000
Transforming to IHS color space...
 100%
Histogram matching...
 100%
 100%
Transforming back to RGB color space and sharpening...
 100%
Assigning grey equalized color tables to output images...
setting pan-sharpened channels to equalized grey scale
Adjusting blue channel color table...
Traceback (most recent call last):
  File "/home/mneteler/software/grass78_git/dist.x86_64-pc-linux-gnu/scripts/i.pansharpen", line 632, in <module>
    main()
  File "/home/mneteler/software/grass78_git/dist.x86_64-pc-linux-gnu/scripts/i.pansharpen", line 280, in main
    bc.stdin.write('\n'.join(blue_colors))
TypeError: a bytes-like object is required, not 'str'
```

**Comment by neteler** [comment]
All working now. Backported to G7.8 & thanks!
