### ISSUE TITLE
[Bug] error when exporting animation as gif from g.gui.animation

### ISSUE THREAD

**Issue by veroandreo** [OSGeo/grass#827]
**Describe the bug**
When trying to export an animation as gif out of g.gui.animation, I get the following:

![image](https://user-images.githubusercontent.com/20075188/88319046-e8193a80-cd1b-11ea-8aa0-fc6a867f507c.png)

Exporting as .avi works fine, though

**System description:**
```
GRASS version: 7.8.3                                                            
Code revision: exported                                                         
Build date: 2020-06-26                                                          
Build platform: x86_64-redhat-linux-gnu                                         
GDAL: 3.0.4                                                                     
PROJ: 6.3.2                                                                     
GEOS: 3.8.1                                                                     
SQLite: 3.32.3                                                                  
Python: 3.8.3                                                                   
wxPython: 4.0.7                                                                 
Platform: Linux-5.7.8-200.fc32.x86_64-x86_64-with-glibc2.2.5  
```

**Comment by petrasovaa** [comment]
I believe the tplot error was solved in #690

**Comment by petrasovaa** [comment]
If you have Pillow >= 3.4.0, export to GIF should work (works for me). Otherwise it uses a different implementation, which produces the error you posted.

**Comment by veroandreo** [comment]
> I believe the tplot error was solved in #690

Indeed, I don't get this error in grass-dev. Was it backported?

**Comment by veroandreo** [comment]
> If you have Pillow >= 3.4.0, export to GIF should work (works for me). Otherwise it uses a different implementation, which produces the error you posted.

My system reports python3-pillow-7.0.0-4.fc32.x86_64 installed. How to know if it uses (or needs) something else? I get the same error in grass-dev

**Comment by petrasovaa** [comment]
> > I believe the tplot error was solved in #690
> 
> Indeed, I don't get this error in grass-dev. Was it backported?

Yes

**Comment by petrasovaa** [comment]
try:
```
from PIL import PILLOW_VERSION
print(PILLOW_VERSION)
```

**Comment by veroandreo** [comment]
Seems PILLOW_VERSION is deprecated (https://github.com/python-pillow/Pillow/issues/3082). 
Only `help(PIL)` or `PIL.__version__` gave me some info, and PIL.__version__ says 7.0.0 (same that `dnf provides python3-pillow` had said)

**Comment by neteler** [comment]
Test with NC sample data:

https://grass.osgeo.org/download/data/#SpecialTopicDatasets
--> Time series - MODIS Land Surface Temperature mapset

```
cd ~/grassdata/nc_spm_08_grass7/
wget https://grass.osgeo.org/sampledata/north_carolina/nc_spm_mapset_modis2015_2016_lst.zip
unzip nc_spm_mapset_modis2015_2016_lst.zip
rm -f nc_spm_mapset_modis2015_2016_lst.zip

# full example for reproduction
grass79 ~/grassdata/nc_spm_08_grass7/modis_lst/
g.extension t.upgrade
t.upgrade
t.list 
t.rast.list LST_Day_monthly

# get e.g. center coordinates for query
g.region -c

# plot (note that this are the scaled LST values, to be converted to Celsius)
g.gui.tplot strds=LST_Day_monthly coordinates=551334.464115,172180.124115 title="Scaled Monthly LST, NC"  xlabel="Time" ylabel="LST"
```
![image](https://user-images.githubusercontent.com/1295172/89939020-a5aa9580-dc17-11ea-9a22-99d3dc807c14.png)

```
# no error here (any more?), just a warning:
g.gui.tplot strds=LST_Day_monthly coordinates=551334.464115,172180.124115 title="Scaled Monthly LST, NC"  xlabel="Time" ylabel="LST" csv=NC_monthly_LST.csv
09:15:06 PM: Debug: Adding duplicate image handler for 'Windows bitmap file'
/home/mneteler/software/grass_master/dist.x86_64-pc-linux-gnu/gui/wxpython/tplot/frame.py:1127: MatplotlibDeprecationWarning: 
The iterable function was deprecated in Matplotlib 3.1 and will be removed in 3.3. Use np.iterable instead.
  if not cbook.iterable(artists):

# export of GIF:
g.gui.animation raster=$(g.list raster pattern="MOD*" sep=comma)
```

![image](https://user-images.githubusercontent.com/1295172/89939608-86f8ce80-dc18-11ea-8fc0-422266ebdccc.png)

Error also here (may contain typos since I used OCR to convert it to text):

```
Error

a bytes-like object is required, not 'str'

Reason: a bytes-like object is required, not ‘str’

Traceback (most recent call last):
File "/home/mneteler/software/grass_master/dist.x86_64-pc-linux-gnu/gui/wxpython/animation/controller. py", line 634, in _export
writeGif(filename=exportinfo['file'], images=pilImages,
File "shome/mneteler/sottware/grass_master/dist.x86_64-pc-linux-gnu/etc/python/grass/imaging/images2gif.py", line 503, in writeGif
writeGifVisvis(filename, images, duration, repeat, **kwargs)
File "/home/mneteler/software/grass_master/dist.x86_64-pc-linux-gnu/etc/python/grass/imaging/images2gif.py". line 614, in writeGifVisvis
gifWriter.writeGiffoFile(fp, images, duration, loops, xy, dispose)
File "/home/mneteler/software/grass_master/dist.x86_64-pc-linux-gnu/etc/python/grass/imaging/images2gif.py", line 440, in writeGifToFile
 fp.write(header)
TypeError: a bytes-like object is required, not 'str'
```

**Comment by veroandreo** [comment]
I applied this patch with `git apply 899.diff` in master, and tested, but I still get the same error as originally reported.
