### ISSUE TITLE
[Bug] db.droptable: Python error

### ISSUE THREAD

**Issue by neteler** [OSGeo/grass#947]
**Describe the bug**
The modules fails with a Python error.

**To Reproduce**
```

# Location: nc_spm_08_grass7
cd scripts/db.droptable/testsuite/

python3 test_db_droptable.py 
Copy vector <roadsmajor@PERMANENT> to current mapset as <myroads>

Traceback (most recent call last):
  File "/home/mneteler/software/grass_master/dist.x86_64-pc-linux-gnu/scripts/db.droptable", line 101, in <module>
    main()
  File "/home/mneteler/software/grass_master/dist.x86_64-pc-linux-gnu/scripts/db.droptable", line 79, in main
    used = grass.db.db_table_in_vector(table)
  File "/home/mneteler/software/grass_master/dist.x86_64-pc-linux-gnu/etc/python/grass/script/db.py", line 204, in db_table_in_vector
    for f in vector_db(vect, stderr=nuldev, env=env).values():
  File "/home/mneteler/software/grass_master/dist.x86_64-pc-linux-gnu/etc/python/grass/script/vector.py", line 49, in vector_db
    s = read_command('v.db.connect', quiet=True, flags='g', map=map, sep=';',
  File "/home/mneteler/software/grass_master/dist.x86_64-pc-linux-gnu/etc/python/grass/script/core.py", line 566, in read_command
    return handle_errors(returncode, stdout, args, kwargs)
  File "/home/mneteler/software/grass_master/dist.x86_64-pc-linux-gnu/etc/python/grass/script/core.py", line 393, in handle_errors
    raise CalledModuleError(module=module, code=code,
grass.exceptions.CalledModuleError: Module run v.db.connect v.db.connect --q -g map=landclass96map@user1 sep=; ended with error
Process ended with non-zero return code 1. See errors in the (error) output.

F
Forcing ...
Traceback (most recent call last):
  File "/home/mneteler/software/grass_master/dist.x86_64-pc-linux-gnu/scripts/db.droptable", line 101, in <module>
    main()
  File "/home/mneteler/software/grass_master/dist.x86_64-pc-linux-gnu/scripts/db.droptable", line 79, in main
    used = grass.db.db_table_in_vector(table)
  File "/home/mneteler/software/grass_master/dist.x86_64-pc-linux-gnu/etc/python/grass/script/db.py", line 204, in db_table_in_vector
    for f in vector_db(vect, stderr=nuldev, env=env).values():
  File "/home/mneteler/software/grass_master/dist.x86_64-pc-linux-gnu/etc/python/grass/script/vector.py", line 49, in vector_db
    s = read_command('v.db.connect', quiet=True, flags='g', map=map, sep=';',
  File "/home/mneteler/software/grass_master/dist.x86_64-pc-linux-gnu/etc/python/grass/script/core.py", line 566, in read_command
    return handle_errors(returncode, stdout, args, kwargs)
  File "/home/mneteler/software/grass_master/dist.x86_64-pc-linux-gnu/etc/python/grass/script/core.py", line 393, in handle_errors
    raise CalledModuleError(module=module, code=code,
grass.exceptions.CalledModuleError: Module run v.db.connect v.db.connect --q -g map=landclass96map@user1 sep=; ended with error
Process ended with non-zero return code 1. See errors in the (error) output.

FRemoving vector <myroads>

======================================================================
FAIL: test_drop_table_check (__main__.TestDbDropTable)
Drop table check, the column should still be in the table
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mneteler/software/grass_master/dist.x86_64-pc-linux-gnu/etc/python/grass/gunittest/case.py", line 1152, in assertModule
    module.run()
  File "/home/mneteler/software/grass_master/dist.x86_64-pc-linux-gnu/etc/python/grass/pygrass/modules/interface/module.py", line 771, in run
    self.wait()
grass.exceptions.CalledModuleError: Module run db.droptable db.droptable table=myroads ended with error
Process ended with non-zero return code 1. See the following errors:
b'Traceback (most recent call last):\n  File "/home/mneteler/software/grass_master/dist.x86_64-pc-linux-gnu/scripts/db.droptable", line 101, in <module>\n    main()\n  File "/home/mneteler/software/grass_master/dist.x86_64-pc-linux-gnu/scripts/db.droptable", line 79, in main\n    used = grass.db.db_table_in_vector(table)\n  File "/home/mneteler/software/grass_master/dist.x86_64-pc-linux-gnu/etc/python/grass/script/db.py", line 204, in db_table_in_vector\n    for f in vector_db(vect, stderr=nuldev, env=env).values():\n  File "/home/mneteler/software/grass_master/dist.x86_64-pc-linux-gnu/etc/python/grass/script/vector.py", line 49, in vector_db\n    s = read_command(\'v.db.connect\', quiet=True, flags=\'g\', map=map, sep=\';\',\n  File "/home/mneteler/software/grass_master/dist.x86_64-pc-linux-gnu/etc/python/grass/script/core.py", line 566, in read_command\n    return handle_errors(returncode, stdout, args, kwargs)\n  File "/home/mneteler/software/grass_master/dist.x86_64-pc-linux-gnu/etc/python/grass/script/core.py", line 393, in handle_errors\n    raise CalledModuleError(module=module, code=code,\ngrass.exceptions.CalledModuleError: Module run v.db.connect v.db.connect --q -g map=landclass96map@user1 sep=; ended with error\nProcess ended with non-zero return code 1. See errors in the (error) output.\n'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test_db_droptable.py", line 34, in test_drop_table_check
    self.assertModule(module)
  File "/home/mneteler/software/grass_master/dist.x86_64-pc-linux-gnu/etc/python/grass/gunittest/case.py", line 1167, in assertModule
    self.fail(self._formatMessage(msg, stdmsg))
AssertionError: Running <db.droptable> module ended with non-zero return code (1)
Called: db.droptable(table='myroads')
See the following errors:
Traceback (most recent call last):
  File "/home/mneteler/software/grass_master/dist.x86_64-pc-linux-gnu/scripts/db.droptable", line 101, in <module>
    main()
  File "/home/mneteler/software/grass_master/dist.x86_64-pc-linux-gnu/scripts/db.droptable", line 79, in main
    used = grass.db.db_table_in_vector(table)
  File "/home/mneteler/software/grass_master/dist.x86_64-pc-linux-gnu/etc/python/grass/script/db.py", line 204, in db_table_in_vector
    for f in vector_db(vect, stderr=nuldev, env=env).values():
  File "/home/mneteler/software/grass_master/dist.x86_64-pc-linux-gnu/etc/python/grass/script/vector.py", line 49, in vector_db
    s = read_command('v.db.connect', quiet=True, flags='g', map=map, sep=';',
  File "/home/mneteler/software/grass_master/dist.x86_64-pc-linux-gnu/etc/python/grass/script/core.py", line 566, in read_command
    return handle_errors(returncode, stdout, args, kwargs)
  File "/home/mneteler/software/grass_master/dist.x86_64-pc-linux-gnu/etc/python/grass/script/core.py", line 393, in handle_errors
    raise CalledModuleError(module=module, code=code,
grass.exceptions.CalledModuleError: Module run v.db.connect v.db.connect --q -g map=landclass96map@user1 sep=; ended with error
Process ended with non-zero return code 1. See errors in the (error) output.


======================================================================
FAIL: test_drop_table_with_force (__main__.TestDbDropTable)
Drop table with force, the column should not be in the table
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mneteler/software/grass_master/dist.x86_64-pc-linux-gnu/etc/python/grass/gunittest/case.py", line 1152, in assertModule
    module.run()
  File "/home/mneteler/software/grass_master/dist.x86_64-pc-linux-gnu/etc/python/grass/pygrass/modules/interface/module.py", line 771, in run
    self.wait()
grass.exceptions.CalledModuleError: Module run db.droptable db.droptable table=myroads -f ended with error
Process ended with non-zero return code 1. See the following errors:
b'Forcing ...\nTraceback (most recent call last):\n  File "/home/mneteler/software/grass_master/dist.x86_64-pc-linux-gnu/scripts/db.droptable", line 101, in <module>\n    main()\n  File "/home/mneteler/software/grass_master/dist.x86_64-pc-linux-gnu/scripts/db.droptable", line 79, in main\n    used = grass.db.db_table_in_vector(table)\n  File "/home/mneteler/software/grass_master/dist.x86_64-pc-linux-gnu/etc/python/grass/script/db.py", line 204, in db_table_in_vector\n    for f in vector_db(vect, stderr=nuldev, env=env).values():\n  File "/home/mneteler/software/grass_master/dist.x86_64-pc-linux-gnu/etc/python/grass/script/vector.py", line 49, in vector_db\n    s = read_command(\'v.db.connect\', quiet=True, flags=\'g\', map=map, sep=\';\',\n  File "/home/mneteler/software/grass_master/dist.x86_64-pc-linux-gnu/etc/python/grass/script/core.py", line 566, in read_command\n    return handle_errors(returncode, stdout, args, kwargs)\n  File "/home/mneteler/software/grass_master/dist.x86_64-pc-linux-gnu/etc/python/grass/script/core.py", line 393, in handle_errors\n    raise CalledModuleError(module=module, code=code,\ngrass.exceptions.CalledModuleError: Module run v.db.connect v.db.connect --q -g map=landclass96map@user1 sep=; ended with error\nProcess ended with non-zero return code 1. See errors in the (error) output.\n'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test_db_droptable.py", line 43, in test_drop_table_with_force
    self.assertModule(module)
  File "/home/mneteler/software/grass_master/dist.x86_64-pc-linux-gnu/etc/python/grass/gunittest/case.py", line 1167, in assertModule
    self.fail(self._formatMessage(msg, stdmsg))
AssertionError: Running <db.droptable> module ended with non-zero return code (1)
Called: db.droptable(table='myroads', flags='f')
See the following errors:
Forcing ...
Traceback (most recent call last):
  File "/home/mneteler/software/grass_master/dist.x86_64-pc-linux-gnu/scripts/db.droptable", line 101, in <module>
    main()
  File "/home/mneteler/software/grass_master/dist.x86_64-pc-linux-gnu/scripts/db.droptable", line 79, in main
    used = grass.db.db_table_in_vector(table)
  File "/home/mneteler/software/grass_master/dist.x86_64-pc-linux-gnu/etc/python/grass/script/db.py", line 204, in db_table_in_vector
    for f in vector_db(vect, stderr=nuldev, env=env).values():
  File "/home/mneteler/software/grass_master/dist.x86_64-pc-linux-gnu/etc/python/grass/script/vector.py", line 49, in vector_db
    s = read_command('v.db.connect', quiet=True, flags='g', map=map, sep=';',
  File "/home/mneteler/software/grass_master/dist.x86_64-pc-linux-gnu/etc/python/grass/script/core.py", line 566, in read_command
    return handle_errors(returncode, stdout, args, kwargs)
  File "/home/mneteler/software/grass_master/dist.x86_64-pc-linux-gnu/etc/python/grass/script/core.py", line 393, in handle_errors
    raise CalledModuleError(module=module, code=code,
grass.exceptions.CalledModuleError: Module run v.db.connect v.db.connect --q -g map=landclass96map@user1 sep=; ended with error
Process ended with non-zero return code 1. See errors in the (error) output.


----------------------------------------------------------------------
Ran 2 tests in 2.872s
FAILED (failures=2)

```

**Comment by petrasovaa** [comment]
It works for me with latest master.

**Comment by neteler** [comment]
Here it fails (fresh recompile), on my Fedora 32 box:

```
Welcome to GRASS GIS 7.9.dev (2aef82628)
...
g.version -rge
version=7.9.dev
date=2020
revision=2aef82628
build_date=2020-08-29
build_platform=x86_64-pc-linux-gnu
build_off_t_size=8
libgis_revision=0c4f02edf
libgis_date=2020-08-26T05:19:54+00:00
proj=6.3.2
gdal=3.0.4
geos=3.8.1
sqlite=3.33.0

g.gisenv 
MAPSET=user1
GISDBASE=/home/mneteler/grassdata
LOCATION_NAME=nc_spm_08_grass7
GUI=text
DEBUG=0
MEMORYMB=6000
PID=714295


python3 --version
Python 3.8.5
```

`git status` doesn't report any local modifications.

Can anyone else try the test script (see above)?

**Comment by neteler** [comment]
Interesting: in a new, empty mapset it works. Weird...

**Comment by neteler** [comment]
I kind of found it: the `--q` flag used in the test suppressed the real error:

```
g.gisenv set="DEBUG=1"
...
Traceback (most recent call last):
  File "test_db_droptable.py", line 43, in test_drop_table_with_force
    self.assertModule(module)
  File "/home/mneteler/software/grass_master/dist.x86_64-pc-linux-gnu/etc/python/grass/gunittest/case.py", line 1167, in assertModule
    self.fail(self._formatMessage(msg, stdmsg))
AssertionError: Running <db.droptable> module ended with non-zero return code (1)
Called: db.droptable(table='myroads', flags='f')
See the following errors:
D1/1: G_set_program_name(): db.droptable
D1/1: G_set_program_name(): g.gisenv
D1/1: grass.script.core.start_command(): db.connect --q -c
D1/1: G_set_program_name(): db.connect
D1/1: grass.script.core.start_command(): db.connect -g
D1/1: grass.script.core.start_command(): g.message message=Forcing ...
D1/1: G_set_program_name(): g.message
Forcing ...
D1/1: grass.script.core.start_command(): db.describe -c table=myroads
D1/1: grass.script.core.start_command(): g.list --q -m type=vector mapset=.
D1/1: G_set_program_name(): g.list
D1/1: grass.script.core.start_command(): v.db.connect --q -g map=bla@user1 sep=;
...
D1/1: grass.script.core.start_command(): v.db.connect --q -g map=lakes_box@user1 sep=;
D1/1: grass.script.core.start_command(): v.db.connect --q -g map=landclass96_test@user1 sep=;
D1/1: grass.script.core.start_command(): v.db.connect --q -g map=landclass96map@user1 sep=;
Traceback (most recent call last):
  File "/home/mneteler/software/grass_master/dist.x86_64-pc-linux-gnu/scripts/db.droptable", line 101, in <module>
    main()
...

# trying that without --q:

v.db.connect -g map=landclass96map@user1
D1/1: G_set_program_name(): v.db.connect
D1/1: layer number 1, layer name (null)
D1/1: Vect__open_old(): name = landclass96map@user1, mapset = , layer = 1, update = 0, head_only = 0, is_tmp = 0
D1/1: Vect_set_thresh(): thresh = 0.000000
D1/1: dig_spidx_init(), 2 dims
D1/1: G_find_vector2(): name=landclass96map mapset=user1
D1/1: Map: name = landclass96map, mapset = user1, temporary = 0
D1/1: Vector format: 0 (native)
D1/1: Vect_set_thresh(): thresh = 0.000000
D1/1: Vect__read_head(): vector = landclass96map@user1
D1/1: Vect_set_thresh(): thresh = 0.000000
D1/1: Level request = 1
D1/1: V1_open_old_nat(): name = landclass96map mapset = user1
WARNING: Unable to open coor file for vector map <landclass96map@user1>
ERROR: Unable to open vector map <landclass96map@user1>
D1/1: G_set_program_name(): g.gisenv
D1/1: G_set_program_name(): g.gisenv
```

--> Unable to open coor file for vector map <landclass96map@user1>

Broken map, unfortunately not visible. Hence: the test is fine, closing.
