### ISSUE TITLE
[Bug] Unix-like build fails on Mac with System Integrity Protection enabled

### ISSUE THREAD

**Issue by nilason** [OSGeo/grass#980]
**Describe the bug**

A unix-like compilation on mac with System Integrity Protection (SIP) enabled will fail with `dyld: Library not loaded` messages.

This is caused by DYLD_LIBRARY_PATH being ignored. The reason for this can be found in `man dyld`:
> The dynamic linker checks the following environment variables during the launch of each process.
> Note: If System Integrity Protection is enabled, these environment variables are ignored when executing binaries protected by System Integrity Protection.

Example of build error message:
```
...
mkdir -p /Volumes/dev/grass/dist.x86_64-apple-darwin19.6.0/docs/html/colortables
GISRC=/Volumes/dev/grass/dist.x86_64-apple-darwin19.6.0/demolocation/.grassrc79 GISBASE=/Volumes/dev/grass/dist.x86_64-apple-darwin19.6.0 PATH="/Volumes/dev/grass/dist.x86_64-apple-darwin19.6.0/bin:/Volumes/dev/grass/dist.x86_64-apple-darwin19.6.0/bin:/Volumes/dev/grass/dist.x86_64-apple-darwin19.6.0/scripts:$PATH" PYTHONPATH="/Volumes/dev/grass/dist.x86_64-apple-darwin19.6.0/etc/python:/Volumes/dev/grass/dist.x86_64-apple-darwin19.6.0/gui/wxpython:$PYTHONPATH" DYLD_LIBRARY_PATH="/Volumes/dev/grass/dist.x86_64-apple-darwin19.6.0/bin:/Volumes/dev/grass/dist.x86_64-apple-darwin19.6.0/bin:/Volumes/dev/grass/dist.x86_64-apple-darwin19.6.0/scripts:/Volumes/dev/grass/dist.x86_64-apple-darwin19.6.0/lib:/Volumes/dev/grass/dist.x86_64-apple-darwin19.6.0/lib:" LC_ALL=C LANG=C LANGUAGE=C  /Volumes/dev/grass/tools/thumbnails.py
dyld: Library not loaded: /usr/local/grass79/lib/libgrass_gis.7.9.dylib
  Referenced from: /Volumes/dev/grass/dist.x86_64-apple-darwin19.6.0/bin/g.gisenv
  Reason: image not found
Traceback (most recent call last):
  File "/Volumes/dev/grass/tools/thumbnails.py", line 187, in <module>
    main()
  File "/Volumes/dev/grass/tools/thumbnails.py", line 167, in main
    grass.use_temp_region()
  File "/Volumes/dev/grass/dist.x86_64-apple-darwin19.6.0/etc/python/grass/script/core.py", line 1283, in use_temp_region
    run_command("g.region", flags="u", save=name, overwrite=True)
  File "/Volumes/dev/grass/dist.x86_64-apple-darwin19.6.0/etc/python/grass/script/core.py", line 490, in run_command
    ps = start_command(*args, **kwargs)
  File "/Volumes/dev/grass/dist.x86_64-apple-darwin19.6.0/etc/python/grass/script/core.py", line 439, in start_command
    if debug_level() > 0:
  File "/Volumes/dev/grass/dist.x86_64-apple-darwin19.6.0/etc/python/grass/script/core.py", line 1743, in debug_level
    _debug_level = int(gisenv().get('DEBUG', 0))
  File "/Volumes/dev/grass/dist.x86_64-apple-darwin19.6.0/etc/python/grass/script/core.py", line 1142, in gisenv
    s = read_command("g.gisenv", flags='n', env=env)
  File "/Volumes/dev/grass/dist.x86_64-apple-darwin19.6.0/etc/python/grass/script/core.py", line 566, in read_command
    return handle_errors(returncode, stdout, args, kwargs)
  File "/Volumes/dev/grass/dist.x86_64-apple-darwin19.6.0/etc/python/grass/script/core.py", line 393, in handle_errors
    raise CalledModuleError(module=module, code=code,
grass.exceptions.CalledModuleError: Module run g.gisenv g.gisenv -n ended with error
Process ended with non-zero return code -6. See errors in the (error) output.
dyld: Library not loaded: /usr/local/grass79/lib/libgrass_manage.7.9.dylib
  Referenced from: /Volumes/dev/grass/dist.x86_64-apple-darwin19.6.0/bin/g.remove
  Reason: image not found
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/Volumes/dev/grass/tools/thumbnails.py", line 28, in cleanup
    grass.run_command('g.remove', flags='f', type='raster',
  File "/Volumes/dev/grass/dist.x86_64-apple-darwin19.6.0/etc/python/grass/script/core.py", line 501, in run_command
    return handle_errors(returncode, result=None, args=args, kwargs=kwargs)
  File "/Volumes/dev/grass/dist.x86_64-apple-darwin19.6.0/etc/python/grass/script/core.py", line 393, in handle_errors
    raise CalledModuleError(module=module, code=code,
grass.exceptions.CalledModuleError: Module run g.remove g.remove --q -f type=raster name=tmp_grad_rel_13332 ended with error
Process ended with non-zero return code -6. See errors in the (error) output.
make[4]: [thumbnails] Error 1 (ignored)
...
```

**System description (please complete the following information):**

- Operating System: macOS 10.15 (but this issue will probably go back a few versions, maybe as far back as 10.11 when SIP was introduced)
- GRASS GIS version: 7.8+

**Additional context**
This issue may be solved by using dynamic linking with `@rpath` instead of `DYLD_LIBRARY_PATH`.

**Comment by neteler** [comment]
Merge done, @nilason please ping me once you need the backport.
